import { useNavigate } from "react-router-dom";
import { useState, useEffect, useRef } from "react";

const DocSMS=({from,time,message})=>(<div style={{background:"#1a1a2e",borderRadius:16,padding:"1rem",maxWidth:320,border:"2px solid #2a2a4a",marginBottom:"1rem"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8,paddingBottom:6,borderBottom:"1px solid #2a2a4a"}}><span style={{fontWeight:700,fontSize:".85rem",color:"#fff"}}>{from}</span><span style={{fontSize:".7rem",color:"#888",fontFamily:"monospace"}}>{time}</span></div><div style={{background:"#0066cc",color:"#fff",padding:".6rem .9rem",borderRadius:"14px 14px 4px 14px",fontSize:".85rem",lineHeight:1.45,maxWidth:"90%"}}>{message}</div></div>);

const DocPanneau=({title,lines,icon,color})=>(<div style={{background:"#fff",color:"#222",borderRadius:8,padding:"1rem 1.2rem",maxWidth:350,borderLeft:`5px solid ${color||"#c0392b"}`,marginBottom:"1rem",boxShadow:"0 2px 8px rgba(0,0,0,.2)"}}>{icon&&<div style={{fontSize:"1.5rem",marginBottom:4}}>{icon}</div>}{title&&<div style={{color:"#fff",fontWeight:700,fontSize:".8rem",padding:".3rem .6rem",borderRadius:4,display:"inline-block",marginBottom:8,background:color||"#c0392b"}}>{title}</div>}<div style={{fontSize:".85rem",lineHeight:1.5}}>{lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>);

const DocMenu=({restaurant,items,footer})=>(<div style={{background:"#1c0a00",color:"#f0e6d3",borderRadius:10,padding:"1.2rem",maxWidth:320,marginBottom:"1rem",border:"1px solid #3a2515"}}><div style={{fontWeight:700,fontSize:".9rem",textAlign:"center",marginBottom:8,paddingBottom:8,borderBottom:"1px solid #3a2515"}}>{restaurant}</div>{items.map((it,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",fontSize:".82rem",marginBottom:3}}><span>{it.name}</span>{it.price&&<span style={{color:"#d4a574",fontFamily:"monospace",fontWeight:700}}>{it.price}</span>}</div>)}{footer&&<div style={{marginTop:8,paddingTop:8,borderTop:"1px solid #3a2515",fontSize:".75rem",textAlign:"center",color:"#a0886e"}}>{footer}</div>}</div>);

const DocBillet=({lines})=>(<div style={{background:"#f5f0e8",color:"#333",borderRadius:8,maxWidth:380,marginBottom:"1rem",overflow:"hidden",border:"1px dashed #ccc"}}><div style={{background:"#1a3a5c",color:"#fff",padding:".5rem .8rem",fontFamily:"monospace",fontSize:".75rem",fontWeight:700}}>BILLET</div><div style={{padding:".8rem",fontSize:".82rem",lineHeight:1.6}}>{lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>);

const DocLettre=({header,body,signature})=>(<div style={{background:"#fefdf8",color:"#333",borderRadius:6,padding:"1.2rem",maxWidth:500,marginBottom:"1rem",border:"1px solid #ddd",fontSize:".85rem",lineHeight:1.6}}>{header&&<div style={{fontWeight:700,fontSize:".82rem",color:"#555",marginBottom:8,paddingBottom:8,borderBottom:"1px solid #eee"}}>{header}</div>}<div style={{whiteSpace:"pre-line"}}>{body}</div>{signature&&<div style={{marginTop:"1rem",paddingTop:8,borderTop:"1px solid #eee",fontStyle:"italic",color:"#666",fontSize:".8rem",whiteSpace:"pre-line"}}>{signature}</div>}</div>);

const DocAffiche=({title,lines,color})=>(<div style={{background:"#0d1425",borderRadius:10,padding:"1.2rem",maxWidth:380,marginBottom:"1rem",border:`2px solid ${color||"#2980b9"}`,textAlign:"center"}}><div style={{fontWeight:800,fontSize:"1rem",marginBottom:8,color:color||"#2980b9"}}>{title}</div><div style={{fontSize:".85rem",lineHeight:1.5,color:"#e2e8f0"}}>{lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>);

const DocEmail=({from,to,subject,body})=>(<div style={{background:"#f8f9fa",color:"#333",borderRadius:8,padding:"1rem",maxWidth:480,marginBottom:"1rem",border:"1px solid #ddd",fontSize:".82rem",lineHeight:1.5}}><div style={{padding:"2px 0",borderBottom:"1px solid #eee"}}><b style={{color:"#666",fontSize:".75rem"}}>De :</b> {from}</div><div style={{padding:"2px 0",borderBottom:"1px solid #eee"}}><b style={{color:"#666",fontSize:".75rem"}}>{"\u00c0"} :</b> {to}</div><div style={{padding:"2px 0",borderBottom:"1px solid #eee"}}><b style={{color:"#666",fontSize:".75rem"}}>Objet :</b> <strong>{subject}</strong></div><div style={{marginTop:8,whiteSpace:"pre-line"}}>{body}</div></div>);

const DocArticle=({source,title,body})=>(<div style={{background:"#0d1425",borderRadius:8,padding:"1.2rem",maxWidth:600,marginBottom:"1rem",border:"1px solid rgba(0,212,255,.1)"}}>{source&&<div style={{fontFamily:"monospace",fontSize:".65rem",color:"#00d4ff",textTransform:"uppercase",letterSpacing:".05em",marginBottom:8}}>{source}</div>}{title&&<div style={{fontWeight:700,fontSize:".95rem",marginBottom:8,color:"#fff"}}>{title}</div>}<div style={{fontSize:".85rem",lineHeight:1.65,color:"#94a3b8"}}>{body}</div></div>);

const DocNote=({body})=>(<div style={{background:"#fff9c4",color:"#333",borderRadius:6,padding:"1rem",maxWidth:320,marginBottom:"1rem",boxShadow:"2px 2px 8px rgba(0,0,0,.15)",transform:"rotate(-1deg)",position:"relative"}}><div style={{position:"absolute",top:-8,left:"50%",transform:"translateX(-50%)",fontSize:"1.2rem"}}>{"\ud83d\udccc"}</div><div style={{fontSize:".85rem",lineHeight:1.5,whiteSpace:"pre-line",paddingTop:4}}>{body}</div></div>);

const Doc=({d})=>{if(!d)return null;const M={sms:DocSMS,panneau:DocPanneau,menu:DocMenu,billet:DocBillet,lettre:DocLettre,affiche:DocAffiche,email:DocEmail,article:DocArticle,note:DocNote};const C=M[d.type];return C?<C {...d}/>:<DocArticle body={d.body}/>};


const Q=[

    {id:1, doc:{type:"sms",from:"Air Canada",time:"06:12",message:"⚠️ Vol AC 845 Montréal→Vancouver : retard de 2h. Nouveau départ : 16h30. Gate changée : C22 (ancienne B12). Présentez-vous 30 min avant."}, q:"À quelle gate le passager doit-il se rendre ?", o:["B12.","C22.","B22.","C12."], c:1},
    {id:2, doc:{type:"panneau",title:"MAGASIN SPORT+",lines:["SOLDES DE FIN DE SAISON","40 % sur vêtements d'hiver","20 % sur équipement de ski","Chaussures : 2ᵉ paire à moitié prix","⚠️ Aucun échange ni remboursement sur les soldes"],color:"#e91e63"}, q:"Peut-on échanger un article acheté en solde ?", o:["Oui, dans les 30 jours.","Non, aucun échange ni remboursement.","Oui, avec le reçu.","Oui, mais seulement contre un crédit."], c:1},
    {id:3, doc:{type:"email",from:"Banque TD",to:"s.kumar@mail.ca",subject:"Alerte de sécurité",body:"Un achat de 487,32 $ a été effectué chez ElectroMax à 08:42 avec votre carte se terminant par 4491.\n\nSi vous reconnaissez cette transaction, aucune action n'est requise. Si ce n'est pas vous, appelez immédiatement le 1-888-555-0100 pour bloquer votre carte."}, q:"Que doit faire M. Kumar s'il n'a pas fait cet achat ?", o:["Ignorer le message.","Appeler le 1-888-555-0100 pour bloquer sa carte.","Se rendre en succursale le lendemain.","Envoyer un courriel à la banque."], c:1},
    {id:4, doc:{type:"affiche",title:"PORTES OUVERTES — GARDERIE LES PETITS SOLEILS",lines:["Samedi 15 mars — 10h à 14h","Visite des locaux et rencontre avec l'équipe","Places disponibles à partir de septembre","Enfants de 18 mois à 5 ans"],color:"#ff9800"}, q:"Un enfant de 6 ans peut-il être inscrit ?", o:["Oui, la garderie accepte tous les âges.","Non, la garderie accueille les enfants de 18 mois à 5 ans.","Oui, à partir de septembre.","Non, seulement les bébés de moins de 18 mois."], c:1},
    {id:5, doc:{type:"note",body:"Antoine,\nLe plombier est passé à 11h. Il a réparé la fuite sous l'évier mais dit que le chauffe-eau doit être remplacé. Il reviendra mardi avec un devis. J'ai payé 85 $ pour l'intervention d'aujourd'hui (reçu sur le comptoir).\n— Camille"}, q:"Que reste-t-il à faire ?", o:["Réparer la fuite sous l'évier.","Obtenir un devis pour remplacer le chauffe-eau.","Payer le plombier pour l'intervention.","Appeler un autre plombier."], c:1},
    {id:6, doc:{type:"panneau",lines:["📚 LIBRAIRIE — Horaires spéciaux","Lundi 24 mars : FERMÉE (inventaire)","Mardi 25 au vendredi 28 : 10h – 18h","Samedi 29 : 10h – 17h","Dimanche 30 : 12h – 17h"],color:"#795548"}, q:"La librairie est-elle ouverte le lundi 24 mars ?", o:["Oui, aux horaires normaux.","Non, elle est fermée pour inventaire.","Oui, mais seulement l'après-midi.","Non, elle est fermée tout le week-end."], c:1},
    {id:7, doc:{type:"billet",lines:["CINÉMA BEAUBIEN","Film : LES ENFANTS DU FLEUVE","Salle 3 — Rangée F — Siège 12","Séance : 19h15 — Durée : 2h05","Tarif étudiant : 10,50 $","⚠️ Porte fermée 10 min après le début"]}, q:"Jusqu'à quelle heure peut-on entrer dans la salle ?", o:["19h15 exactement.","19h25.","19h00.","21h20."], c:1},
    {id:8, doc:{type:"panneau",title:"RECYCLAGE — CONSIGNES",lines:["Bac BLEU : papier, carton (propres et secs)","Bac VERT : verre, métal, plastiques #1 à #5","⚠️ Plastiques #6 et #7 : NON recyclables","Bac BRUN : résidus alimentaires"],color:"#4caf50"}, q:"Où mettre un contenant en plastique #6 ?", o:["Dans le bac vert.","Dans le bac bleu.","Dans le bac brun.","Dans aucun bac de recyclage (il n'est pas recyclable)."], c:3},
    {id:9, doc:{type:"sms",from:"Clinique médicale",time:"15:30",message:"Rappel : votre RDV avec Dr Tremblay est demain à 8h45. Merci d'arriver 15 min en avance avec votre carte RAMQ. Pour annuler : répondez STOP (48h à l'avance minimum)."}, q:"Peut-on annuler ce rendez-vous maintenant ?", o:["Oui, en répondant STOP.","Non, il faut annuler 48h à l'avance et le RDV est demain.","Oui, mais seulement par téléphone.","Non, les rendez-vous ne sont jamais annulables."], c:1},
    {id:10, doc:{type:"affiche",title:"MARCHÉ FERMIER",lines:["Tous les samedis de mai à octobre","8h00 – 13h00","Parc des Cèdres — Entrée libre","Producteurs locaux · Artisans · Food trucks","🐕 Chiens en laisse bienvenus"],color:"#8bc34a"}, q:"Le marché a-t-il lieu en hiver ?", o:["Oui, toute l'année.","Non, seulement de mai à octobre.","Oui, mais seulement en intérieur.","Non, seulement en été (juin à août)."], c:1},
    // B1/B2
    {id:11, doc:{type:"article",source:"Le Devoir — Transport",body:"La STM a annoncé une hausse de 8 % du tarif mensuel du métro, le portant à 101,50 $. La Société justifie cette augmentation par la hausse des coûts d'entretien du réseau vieillissant. Les groupes de défense des usagers notent que la fréquentation a baissé de 12 % depuis la pandémie et craignent qu'une hausse de prix n'aggrave cette tendance."}, q:"Quel cercle vicieux les groupes d'usagers redoutent-ils ?", o:["Que les bus soient supprimés.","Que la hausse de prix fasse fuir les usagers, réduisant encore les revenus.","Que les employés fassent grève.","Que le gouvernement privatise la STM."], c:1},
    {id:12, doc:{type:"article",source:"Radio-Canada — Technologie",body:"L'IA est désormais utilisée pour rédiger les premières ébauches de jugements dans les petites créances au Québec. Le juge conserve la décision finale. Les avocats sont divisés : certains y voient un gain d'efficacité considérable pour un système judiciaire engorgé ; d'autres s'inquiètent que les juges, par habitude, valident les recommandations de l'IA sans les remettre en question."}, q:"Quelle inquiétude certains avocats expriment-ils ?", o:["Que l'IA commette des erreurs grammaticales dans les jugements.","Que les juges acceptent automatiquement les recommandations de l'IA sans esprit critique.","Que les avocats perdent leur emploi.","Que les accusés refusent d'être jugés par une machine."], c:1},
    {id:13, doc:{type:"article",source:"La Presse — Éducation",body:"Le gouvernement veut rendre obligatoire un cours de culture financière au secondaire : budget, crédit, investissement, fiscalité. Les enseignants de mathématiques, à qui on confierait le cours, protestent : « Nous ne sommes pas des conseillers financiers. » Les syndicats demandent une formation spécifique et un allègement de la charge d'enseignement existante."}, q:"Pourquoi les enseignants de mathématiques résistent-ils ?", o:["Parce qu'ils jugent la finance inintéressante.","Parce qu'ils ne sont pas formés pour enseigner la finance et craignent une surcharge.","Parce qu'ils veulent un salaire plus élevé.","Parce que la culture financière est déjà au programme."], c:1},
    {id:14, doc:{type:"article",source:"Le Soleil — Environnement",body:"Le caribou forestier du Québec est officiellement en voie de disparition : il ne reste que 5 600 individus, contre 35 000 dans les années 1990. La principale cause est la destruction de son habitat par l'industrie forestière. Le gouvernement hésite entre protéger l'habitat (ce qui réduirait les coupes) et protéger les emplois de 60 000 travailleurs forestiers."}, q:"Quel dilemme le gouvernement affronte-t-il ?", o:["Choisir entre deux espèces animales à protéger.","Arbitrer entre la protection de l'habitat du caribou et les emplois forestiers.","Décider s'il faut interdire la chasse au caribou.","Déterminer si le caribou est réellement en danger."], c:1},
    {id:15, doc:{type:"article",source:"Le Journal de Montréal — Société",body:"Le phénomène des « parents hélicoptères » — ces parents qui surveillent excessivement leurs enfants — a un prolongement universitaire : les « parents tondeuse », qui interviennent directement auprès des professeurs pour contester les notes de leurs enfants adultes. Les universités rapportent une hausse de 40 % des plaintes parentales en cinq ans."}, q:"Que font les « parents tondeuse » ?", o:["Ils aident leurs enfants à étudier.","Ils contestent directement les notes auprès des professeurs universitaires.","Ils financent les études de leurs enfants.","Ils choisissent les cours à la place de leurs enfants."], c:1},
    {id:16, doc:{type:"article",source:"Radio-Canada — Économie",body:"Le port de Montréal investit 750 millions $ pour moderniser ses installations. Mais un obstacle inattendu freine les travaux : la découverte de sols contaminés au plomb et aux hydrocarbures sur 40 % de la zone de construction. La décontamination pourrait ajouter 200 millions $ au budget et un retard de deux ans."}, q:"Quel obstacle imprévu le port de Montréal rencontre-t-il ?", o:["Des conflits avec les syndicats.","La contamination des sols sur une grande partie du chantier.","L'opposition des résidents du quartier.","Le manque de financement fédéral."], c:1},
    {id:17, doc:{type:"article",source:"Le Devoir — Alimentation",body:"Le Québec est le plus grand producteur de canneberges au Canada, mais 85 % de la production est exportée vers les États-Unis et l'Europe. Paradoxalement, les canneberges vendues dans les supermarchés québécois proviennent souvent du Wisconsin, car les contrats d'exportation à long terme empêchent les producteurs locaux de servir leur propre marché."}, q:"Pourquoi les Québécois mangent-ils des canneberges américaines ?", o:["Les canneberges québécoises sont de moindre qualité.","Les producteurs locaux sont liés par des contrats d'exportation à long terme.","Le Wisconsin produit plus de canneberges que le Québec.","Le transport des canneberges québécoises est trop coûteux."], c:1},
    {id:18, doc:{type:"article",source:"La Presse — Santé",body:"Le Québec a ouvert 15 « mini-urgences » (cliniques ouvertes 24h/24 pour les cas non vitaux) pour désengorger les urgences hospitalières. Les résultats sont mitigés : les mini-urgences sont très fréquentées, mais 30 % des patients y sont redirigés vers l'hôpital, ce qui leur fait perdre du temps et surcharge les ambulances de transfert."}, q:"Pourquoi les mini-urgences ne résolvent-elles pas entièrement le problème ?", o:["Personne ne les utilise.","Un tiers des patients doivent être redirigés vers l'hôpital, créant des pertes de temps.","Elles ferment trop tôt le soir.","Les médecins refusent d'y travailler."], c:1},
    {id:19, doc:{type:"article",source:"Le Devoir — Immigration",body:"Le programme d'Entrée express du Canada priorise les candidats qui ont une offre d'emploi validée. Or, obtenir cette offre nécessite souvent un permis de travail... qui nécessite d'être au Canada... ce qui nécessite un visa... qui est facilité par Entrée express. Ce cercle vicieux administratif piège des candidats qualifiés dans un labyrinthe de pré-requis mutuels."}, q:"Quel problème le programme d'immigration crée-t-il ?", o:["Les candidats ne veulent pas venir au Canada.","Un cercle vicieux où chaque étape requiert le résultat d'une étape ultérieure.","Les offres d'emploi sont trop rares au Canada.","Le gouvernement a suspendu le programme."], c:1},
    {id:20, doc:{type:"article",source:"Québec Science — Santé",body:"Des chercheurs de l'Université de Sherbrooke ont découvert que les microplastiques traversent la barrière intestinale et atteignent le sang. Leurs concentrations sont 10 fois plus élevées chez les consommateurs réguliers de plats préparés dans des contenants en plastique. L'impact sanitaire reste incertain, mais les chercheurs recommandent par précaution de privilégier les contenants en verre ou en acier."}, q:"Que recommandent les chercheurs malgré l'incertitude ?", o:["D'arrêter de manger des plats préparés.","De privilégier les contenants en verre ou en acier.","D'attendre les résultats définitifs avant de changer ses habitudes.","De prendre des compléments alimentaires."], c:1},
    {id:21, doc:{type:"article",source:"Le Devoir — Culture",body:"La Bibliothèque nationale du Québec numérise ses archives, mais un dilemme éthique se pose : certains documents historiques contiennent des propos racistes ou des caricatures offensantes. Faut-il les numériser tels quels (au risque de banaliser ces propos), les contextualiser (ce qui demande un travail colossal) ou les censurer (ce qui altérerait le registre historique) ?"}, q:"Quel est le dilemme posé par la numérisation ?", o:["Le coût de la numérisation est trop élevé.","Comment traiter les contenus offensants : numériser, contextualiser ou censurer.","Les documents sont en trop mauvais état pour être numérisés.","Les citoyens ne s'intéressent pas aux archives."], c:1},
    {id:22, doc:{type:"article",source:"La Presse — Urbanisme",body:"La Ville de Laval a autorisé la construction de « mini-maisons » (moins de 40 m²) sur des terrains résidentiels existants. Les promoteurs de la densification douce y voient une solution au manque de logements abordables. Les voisins, eux, craignent une dévalorisation de leur propriété et une surcharge des infrastructures (stationnement, égouts, écoles)."}, q:"Pourquoi les voisins s'opposent-ils aux mini-maisons ?", o:["Elles sont trop petites pour être habitables.","Ils craignent la dévalorisation de leur propriété et la surcharge des infrastructures.","Elles sont construites avec des matériaux dangereux.","La ville n'a pas consulté les résidents."], c:1},
    {id:23, doc:{type:"article",source:"Radio-Canada — Tourisme",body:"Le tourisme de masse menace le village de Percé : 300 000 visiteurs par an pour 3 000 résidents permanents. Les prix de l'immobilier ont doublé en cinq ans, poussés par les locations Airbnb. Les jeunes du village ne peuvent plus se loger localement. Le paradoxe : l'économie locale dépend du tourisme, mais le tourisme détruit le mode de vie qu'il est venu chercher."}, q:"Quel paradoxe l'article décrit-il ?", o:["Le tourisme enrichit les résidents de Percé.","Le tourisme détruit le mode de vie authentique qu'il venait chercher.","Les touristes ne dépensent pas assez à Percé.","Les résidents ne veulent plus de touristes."], c:1},
    {id:24, doc:{type:"article",source:"Le Devoir — Justice",body:"Le Québec a instauré un registre public des délinquants sexuels, accessible en ligne. Les partisans y voient une protection nécessaire du public. Les criminologues mettent en garde : les études montrent que ces registres n'ont aucun effet mesurable sur la récidive et peuvent même la favoriser en rendant la réinsertion impossible (refus de logement, de travail)."}, q:"Quel effet pervers les registres de délinquants peuvent-ils avoir selon les criminologues ?", o:["Les victimes se sentent moins en sécurité.","Ils empêchent la réinsertion, ce qui pourrait favoriser la récidive.","Ils violent la présomption d'innocence.","Ils sont consultés par trop peu de personnes."], c:1},
    // C1/C2
    {id:25, doc:{type:"article",source:"Essai — Méritocratie numérique",body:"La méritocratie algorithmique représente une mutation : ce n'est plus la société qui juge le mérite, mais un système opaque dont les critères sont inconnus de ceux qu'il évalue. Quand un CV est rejeté par un algorithme, le candidat ne sait pas pourquoi. La méritocratie classique avait au moins la décence de nommer ses critères ; la méritocratie algorithmique évalue sans rendre de comptes."}, q:"Quelle différence l'auteur établit-il entre méritocratie classique et algorithmique ?", o:["La méritocratie algorithmique est plus juste.","La méritocratie classique rendait ses critères visibles, contrairement à l'algorithmique.","La méritocratie algorithmique ne s'applique qu'au monde du travail.","Il n'y a aucune différence significative entre les deux."], c:1},
    {id:26, doc:{type:"text",body:"Ce qui l'avait toujours frappé dans les aéroports, c'était cette égalité provisoire entre les êtres. Pendant quelques heures, cadres, étudiants, familles et solitaires partageaient un même non-lieu, soumis aux mêmes annonces, aux mêmes retards, à la même attente. L'aéroport abolissait les hiérarchies — non par vertu, mais par indifférence."}, q:"Comment l'aéroport « abolit-il les hiérarchies » selon le narrateur ?", o:["En offrant le même confort à tous les passagers.","Par une indifférence qui soumet chacun aux mêmes contraintes.","En interdisant les classes de voyage.","En traitant chaque passager avec un respect égal."], c:1},
    {id:27, doc:{type:"article",source:"Sociologie — Intelligence collective",body:"Le « miracle » de l'intelligence collective exige trois conditions rarement réunies : diversité des perspectives, indépendance des jugements, et agrégation efficace. Quand le conformisme s'installe — quand chacun regarde ce que l'autre pense avant de penser — l'intelligence collective se transforme en « pensée de groupe » : une machine à produire du consensus aveugle."}, q:"Quelle est la condition la plus menacée par le conformisme ?", o:["La diversité des perspectives.","L'indépendance des jugements individuels.","L'efficacité du mécanisme d'agrégation.","La taille du groupe."], c:1},
    {id:28, doc:{type:"article",source:"Psychologie — Effet Dunning-Kruger",body:"L'effet Dunning-Kruger est souvent résumé par « les incompétents se croient compétents ». Mais la recherche originale montre un phénomène plus nuancé : les personnes peu compétentes surestiment modestement leurs capacités, tandis que les experts les sous-estiment légèrement. Le vrai problème n'est pas l'arrogance des ignorants — c'est que la compétence s'accompagne de doute, et l'incompétence de certitude."}, q:"Quelle est la nuance souvent ignorée de l'effet Dunning-Kruger ?", o:["Les incompétents sont conscients de leur incompétence.","Les experts sous-estiment aussi leurs capacités, et le doute accompagne la compétence.","L'effet ne concerne que les tâches intellectuelles.","L'effet disparaît avec l'âge."], c:1},
    {id:29, doc:{type:"article",source:"Philosophie — Accélération",body:"L'accélération sociale n'est pas un fait quantitatif (nous ne « manquons » pas de temps — nous en avons objectivement plus que nos aïeux). C'est un fait qualitatif : le rapport au temps a changé. Quand chaque choix est réversible, chaque engagement temporaire, chaque identité négociable, le temps cesse d'être un fleuve et devient un archipel d'instants déconnectés."}, q:"Quelle est la thèse centrale de l'auteur ?", o:["Nous avons objectivement moins de temps que nos ancêtres.","Le problème n'est pas la quantité de temps mais la transformation de notre rapport au temps.","L'accélération sociale est un mythe.","Il faut revenir à un mode de vie plus lent."], c:1},
    {id:30, doc:{type:"article",source:"Essai — Frontières",body:"Les frontières ne séparent pas des espaces — elles créent des différences de valeur. Un pas de côté, et le même travail vaut dix fois plus ; la même eau est potable ou non ; le même individu est citoyen ou clandestin. La frontière n'est pas un mur entre deux territoires ; c'est un multiplicateur d'inégalités."}, q:"Comment l'auteur définit-il la frontière ?", o:["Comme une protection nécessaire de la souveraineté nationale.","Comme un mécanisme qui crée et amplifie les inégalités.","Comme un vestige du colonialisme à abolir.","Comme un instrument de régulation économique neutre."], c:1},
    {id:31, doc:{type:"article",source:"Neuropsychologie",body:"La mémoire n'est pas un enregistrement — c'est une reconstruction. Chaque rappel d'un souvenir le modifie imperceptiblement : le cerveau comble les lacunes avec des inférences, ajoute des détails post-événement et ajuste le souvenir à l'identité présente du sujet. Le souvenir le plus « vivace » n'est pas nécessairement le plus fidèle — c'est celui qui a été le plus souvent remanié."}, q:"Quel paradoxe la recherche sur la mémoire révèle-t-elle ?", o:["Les souvenirs vagues sont plus fiables que les souvenirs précis.","Les souvenirs les plus vivaces sont ceux qui ont été le plus modifiés par les rappels successifs.","La mémoire s'améliore avec l'âge.","Les souvenirs émotionnels sont toujours exacts."], c:1},
    {id:32, doc:{type:"article",source:"Éthique — Consentement numérique",body:"Le consentement numérique est une fiction juridique. Les 97 % d'utilisateurs qui cliquent « J'accepte » sans lire les conditions ne consentent pas — ils capitulent. La différence entre consentement et capitulation, c'est le pouvoir : quand refuser signifie se couper de services devenus indispensables, le « choix » n'en est plus un."}, q:"Pourquoi l'auteur parle-t-il de « capitulation » plutôt que de « consentement » ?", o:["Parce que les conditions sont rédigées dans un langage inaccessible.","Parce que refuser équivaut à se priver de services indispensables, supprimant le vrai choix.","Parce que les utilisateurs ne savent pas lire.","Parce que les entreprises modifient les conditions sans prévenir."], c:1},
    {id:33, doc:{type:"article",source:"Philosophie de l'éducation",body:"L'approche par compétences réduit l'éducation à une fonction d'adaptation au marché. En évacuant les humanités au profit de compétences mesurables (« pensée critique », « résolution de problèmes »), on produit paradoxalement des individus moins capables de penser de manière critique — car la pensée critique véritable exige une culture générale que la seule « compétence » ne fournit pas."}, q:"Quel paradoxe l'auteur identifie-t-il dans l'approche par compétences ?", o:["Les compétences ne sont pas utiles sur le marché du travail.","En voulant enseigner la pensée critique comme compétence, on la vide de la culture qui la nourrit.","Les humanités sont plus faciles à enseigner que les compétences.","L'approche par compétences est trop difficile pour les étudiants."], c:1},
    {id:34, doc:{type:"article",source:"Écologie — Décroissance",body:"La décroissance n'est pas une récession — c'est une réorganisation délibérée de l'économie autour de la suffisance plutôt que de la croissance. La confondre avec une récession, c'est comme confondre un jeûne volontaire avec une famine. Le défi n'est pas de produire moins mais de décider collectivement ce qui mérite d'être produit."}, q:"Quelle distinction l'auteur établit-il ?", o:["Entre croissance et décroissance.","Entre décroissance choisie (réorganisation) et récession subie (crise).","Entre économie de marché et économie planifiée.","Entre pays riches et pays pauvres."], c:1},
    {id:35, doc:{type:"text",body:"Il ne s'agissait pas de courage. Le courage suppose qu'on a le choix. Ce que Fatima avait fait — traverser la mer sur un radeau de fortune avec ses deux enfants — n'était pas un acte de bravoure mais de calcul : le risque de mourir en mer était inférieur au risque de rester. Quand la seule alternative est la certitude de la souffrance, l'acte le plus fou devient l'acte le plus rationnel."}, q:"Pourquoi l'auteur refuse-t-il de qualifier l'acte de Fatima de « courage » ?", o:["Parce qu'elle n'avait pas de mérite particulier.","Parce que le courage suppose un choix, or elle n'en avait pas.","Parce que son acte était irréfléchi.","Parce qu'elle a mis ses enfants en danger."], c:1},
    {id:36, doc:{type:"article",source:"Philosophie politique — Cosmopolitisme",body:"Le cosmopolitisme éthique sans cosmopolitisme institutionnel est un luxe de privilégiés. Il est facile de se sentir « citoyen du monde » quand on possède un passeport fort, un compte en banque garni et un billet d'avion retour. Pour les millions de déplacés, de réfugiés et de sans-papiers, le « monde » n'est pas un espace ouvert — c'est un labyrinthe de frontières."}, q:"Quelle critique l'auteur adresse-t-il au cosmopolitisme ?", o:["Il est incompatible avec le patriotisme.","C'est un idéal accessible uniquement aux privilégiés, inaccessible aux plus vulnérables.","Il encourage l'immigration illégale.","Il détruit les cultures locales."], c:1},
    {id:37, doc:{type:"article",source:"Essai — Surveillance",body:"La smart city promet l'efficacité — mais l'efficacité au service de qui ? Les capteurs qui optimisent le trafic collectent aussi les déplacements de chaque citoyen. La reconnaissance faciale qui sécurise les rues identifie aussi les manifestants. L'outil est neutre ; l'usage ne l'est jamais. Et dans l'histoire, les outils de surveillance ont toujours fini par servir le pouvoir contre ceux qu'ils prétendaient protéger."}, q:"Quelle leçon historique l'auteur tire-t-il ?", o:["La technologie est toujours bénéfique pour la société.","Les outils de surveillance finissent toujours par servir le pouvoir contre les citoyens.","La smart city est impossible à réaliser techniquement.","Les manifestants doivent être identifiés pour maintenir l'ordre."], c:1},
    {id:38, doc:{type:"article",source:"Essai — Mort de l'auteur",body:"La « mort de l'auteur » de Barthes a libéré l'interprétation. Mais poussée à l'extrême, elle ouvre une boîte de Pandore : si l'intention de l'auteur ne compte plus, alors toute lecture est légitime — y compris celle qui affirme que « 1984 » d'Orwell est un mode d'emploi plutôt qu'une mise en garde. La liberté d'interprétation a besoin, paradoxalement, de limites pour rester féconde."}, q:"Quel risque l'auteur identifie-t-il dans la théorie de Barthes ?", o:["Que les auteurs cessent d'écrire.","Que toute interprétation devienne légitime, y compris les contresens manifestes.","Que les lecteurs ne s'intéressent plus à la littérature.","Que les critiques littéraires perdent leur emploi."], c:1},
    {id:39, doc:{type:"article",source:"Essai final — Langage et pouvoir",body:"Nommer, c'est déjà gouverner. Celui qui décide si un événement est une « crise » ou une « transition », si un groupe est une « minorité » ou une « communauté », si une politique est « réaliste » ou « radicale » — celui-là contrôle le cadre dans lequel les autres doivent penser. Le pouvoir politique le plus profond n'est pas celui qui interdit, mais celui qui définit le vocabulaire dans lequel les choix sont formulés."}, q:"Quel est le pouvoir politique le plus profond selon l'auteur ?", o:["Le pouvoir législatif d'interdire et de sanctionner.","Le pouvoir de définir le vocabulaire qui cadre les choix politiques.","Le pouvoir économique de financer les campagnes électorales.","Le pouvoir médiatique de contrôler l'information."], c:1},
];

function sc(a){let x=0,y=0,z=0;Q.forEach((q,i)=>{const ok=a[i]===q.c;if(i<10&&ok)x++;else if(i<24&&ok)y++;else if(i>=24&&ok)z++});const xp=x/10,yp=y/14,zp=z/15,t=x+y+z,tp=t/39;let n;if(zp>=.8&&yp>=.7)n=tp>=.85?10:tp>=.75?9:8;else if(zp>=.5&&yp>=.6)n=tp>=.65?7:6;else if(yp>=.5&&xp>=.7)n=tp>=.55?6:5;else if(xp>=.7&&yp>=.3)n=4;else if(xp>=.5)n=3;else n=2;const lv=n>=9?"C2":n>=7?"C1":n>=6?"B2":n>=4?"B1":n>=3?"A2":"A1";return{nclc:n,level:lv,total:t,a1a2:x,b1b2:y,c1c2:z,xp,yp,zp}}

const C={bg:"#080c16",s1:"#0d1425",cy:"#00d4ff",ind:"#6366f1",gn:"#10b981",bl:"#3b82f6",rd:"#ef4444",am:"#f59e0b",tx:"#e2e8f0",txm:"#94a3b8",txd:"#64748b"};
const base={fontFamily:"system-ui,sans-serif",background:C.bg,color:C.tx,minHeight:"100vh"};
const b1={fontWeight:700,fontSize:".85rem",letterSpacing:".08em",textTransform:"uppercase",background:`linear-gradient(135deg,${C.cy},${C.ind})`,color:"#fff",border:"none",padding:".9rem 2.5rem",borderRadius:8,cursor:"pointer"};
const b2={fontSize:".8rem",background:"transparent",color:C.txm,border:"1px solid rgba(0,212,255,.15)",padding:".6rem 1.2rem",borderRadius:6,cursor:"pointer",fontFamily:"inherit"};
const b3={...b1,fontSize:".75rem",padding:".6rem 1.2rem",background:`linear-gradient(135deg,${C.gn},#059669)`};

export default function App(){
  const nav=useNavigate();
  const[pg,setPg]=useState("home");
  const[ci,setCi]=useState(0);
  const[ans,setAns]=useState({});
  const[sec,setSec]=useState(3600);
  const[on,setOn]=useState(false);
  const[pop,setPop]=useState(false);
  const[fl,setFl]=useState(new Set());
  const[nv,setNv]=useState(false);
  const[res,setRes]=useState(null);
  const tr=useRef(null);

  useEffect(()=>{if(!on)return;tr.current=setInterval(()=>setSec(p=>{if(p<=1){clearInterval(tr.current);return 0}return p-1}),1000);return()=>clearInterval(tr.current)},[on]);
  useEffect(()=>{if(sec===0&&on){setOn(false);setRes(sc(ans));setPg("results")}},[sec,on,ans]);

  const go=()=>{setAns({});setCi(0);setSec(3600);setOn(true);setFl(new Set());setNv(false);setPg("quiz")};
  const fin=()=>{setOn(false);clearInterval(tr.current);setRes(sc(ans));setPg("results")};
  const pk=(i,j)=>setAns(p=>({...p,[i]:j}));
  const fg=i=>{setFl(p=>{const n=new Set(p);n.has(i)?n.delete(i):n.add(i);return n})};
  const fm=s=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;
  const ct=Object.keys(ans).length;
  const L=["A","B","C","D"];

  if(pg==="home")return(
    <div style={base}><div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",minHeight:"100vh",padding:"2rem",textAlign:"center"}}>
      <div style={{fontSize:".65rem",color:C.cy,letterSpacing:".15em",textTransform:"uppercase",marginBottom:"2rem",fontFamily:"monospace"}}>FLAB GAMES</div>
      <h1 style={{fontSize:"clamp(2rem,7vw,3.5rem)",fontWeight:900,background:`linear-gradient(135deg,#fff,${C.cy},${C.ind})`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",lineHeight:1,marginBottom:8}}>ESCAPE LAB</h1>
      <p style={{fontSize:"clamp(.75rem,2vw,1rem)",color:C.txm,letterSpacing:".15em",textTransform:"uppercase",marginBottom:"1.5rem"}}>S{"\u00e9"}rie Echo {"\u2014"} TCF Canada</p>
      <p style={{fontSize:".9rem",color:C.txd,maxWidth:460,lineHeight:1.6,marginBottom:"2.5rem"}}>39 questions avec vrais pi{"\u00e8"}ges. 60 minutes. A1{"\u2192"}C2.</p>
      <button style={b1} onClick={go}>COMMENCER</button>
      <div style={{display:"flex",gap:"2rem",marginTop:"2.5rem",flexWrap:"wrap",justifyContent:"center"}}>
        {[["39","Questions"],["60","Min"],["NCLC","Score"]].map(([v,l])=>(<div key={l} style={{textAlign:"center"}}><div style={{fontWeight:700,fontSize:"1.3rem",color:C.cy}}>{v}</div><div style={{fontSize:".6rem",color:C.txd,textTransform:"uppercase"}}>{l}</div></div>))}
      </div>
    </div></div>
  );

  if(pg==="quiz"){const q=Q[ci],ll=ci<10?"A1/A2":ci<24?"B1/B2":"C1/C2",lc=ci<10?C.gn:ci<24?C.bl:C.ind,tc=sec<=300?C.rd:sec<=900?C.am:C.cy;
  return(<div style={base}>
    <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:".6rem 1rem",background:C.s1,borderBottom:"1px solid rgba(0,212,255,.1)",position:"sticky",top:0,zIndex:50,flexWrap:"wrap",gap:4}}>
      <span style={{fontWeight:700,fontSize:".75rem",color:C.cy}}>ESCAPE LAB</span>
      <div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontWeight:700,fontSize:"1.1rem",color:tc,fontFamily:"monospace"}}>{fm(sec)}</span><span style={{fontSize:".65rem",color:C.txd,fontFamily:"monospace"}}>{ct}/39</span></div>
      <div style={{display:"flex",gap:4}}>
        <button onClick={()=>fg(ci)} style={{...b2,padding:"4px 8px",borderColor:fl.has(ci)?C.ind:"rgba(0,212,255,.15)",color:fl.has(ci)?C.ind:C.txm}}>{"\u2691"}</button>
        <button onClick={()=>setNv(!nv)} style={{...b2,padding:"4px 8px"}}>{"\u2630"}</button>
      </div>
    </div>
    <div style={{height:3,background:"#121a32"}}><div style={{height:"100%",width:`${(ct/39)*100}%`,background:`linear-gradient(90deg,${C.cy},${C.ind})`,transition:"width .3s"}}/></div>
    <div style={{maxWidth:780,margin:"0 auto",padding:"1.5rem 1rem",display:"flex",flexDirection:"column",minHeight:"calc(100vh - 60px)"}}>
      <span style={{display:"inline-block",padding:"3px 10px",borderRadius:100,fontSize:".6rem",fontWeight:700,marginBottom:12,border:`1px solid ${lc}33`,color:lc,background:`${lc}11`,alignSelf:"flex-start"}}>Q{ci+1} {"\u00b7"} {ll}</span>
      <Doc d={q.doc}/>
      <p style={{fontWeight:600,fontSize:".95rem",marginBottom:12,color:"#fff"}}>{q.q}</p>
      <div style={{display:"flex",flexDirection:"column",gap:8,marginBottom:"1.5rem"}}>
        {q.o.map((o,i)=>(<button key={i} onClick={()=>pk(ci,i)} style={{display:"flex",alignItems:"flex-start",gap:10,padding:".8rem 1rem",background:ans[ci]===i?"rgba(0,212,255,.06)":C.s1,border:`1px solid ${ans[ci]===i?C.cy:"rgba(0,212,255,.1)"}`,borderRadius:8,cursor:"pointer",textAlign:"left",fontFamily:"inherit",fontSize:".85rem",color:C.tx,lineHeight:1.45,transition:"all .15s"}}>
          <span style={{flexShrink:0,width:26,height:26,borderRadius:5,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"monospace",fontWeight:700,fontSize:".7rem",background:ans[ci]===i?C.cy:"#121a32",color:ans[ci]===i?C.bg:C.txd}}>{L[i]}</span>
          <span>{o}</span>
        </button>))}
      </div>
      <div style={{display:"flex",justifyContent:"space-between",marginTop:"auto",paddingTop:"1rem",gap:8}}>
        <button style={{...b2,opacity:ci===0?.3:1}} onClick={()=>setCi(Math.max(0,ci-1))} disabled={ci===0}>{"\u2190"} Pr{"\u00e9"}c.</button>
        {ci<38?<button style={b2} onClick={()=>setCi(ci+1)}>Suiv. {"\u2192"}</button>:<button style={b3} onClick={()=>setPop(true)}>TERMINER</button>}
      </div>
    </div>
    {nv&&<div onClick={e=>{if(e.target===e.currentTarget)setNv(false)}} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.6)",zIndex:100,display:"flex",justifyContent:"flex-end"}}>
      <div style={{width:"min(360px,88vw)",background:C.s1,padding:"1.2rem",overflowY:"auto",borderLeft:"1px solid rgba(0,212,255,.1)"}}>
        <div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><span style={{fontWeight:700,fontSize:".8rem",color:C.cy}}>NAVIGATION</span><button style={{...b2,padding:"2px 8px"}} onClick={()=>setNv(false)}>{"\u2715"}</button></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(38px,1fr))",gap:5,marginBottom:12}}>
          {Q.map((_,i)=>(<div key={i} onClick={()=>{setCi(i);setNv(false)}} style={{aspectRatio:"1",borderRadius:5,border:`1px solid ${i===ci?C.cy:ans[i]!=null?C.cy+"40":"rgba(0,212,255,.1)"}`,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"monospace",fontSize:".65rem",fontWeight:700,cursor:"pointer",background:ans[i]!=null?C.cy+"1a":"#121a32",color:ans[i]!=null?C.cy:C.txd,boxShadow:i===ci?`0 0 8px ${C.cy}40`:"none",position:"relative"}}>{i+1}{fl.has(i)&&<span style={{position:"absolute",top:-2,right:1,fontSize:".5rem",color:C.am}}>{"\u2691"}</span>}</div>))}
        </div>
        <button style={{...b3,width:"100%"}} onClick={()=>{setNv(false);setPop(true)}}>TERMINER</button>
      </div>
    </div>}
    {pop&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.7)",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",padding:"1rem"}}>
      <div style={{background:C.s1,border:"1px solid rgba(0,212,255,.1)",borderRadius:14,padding:"1.8rem",maxWidth:400,width:"100%",textAlign:"center"}}>
        <div style={{fontSize:"2rem",marginBottom:8}}>{"\u26a0\ufe0f"}</div>
        <div style={{fontWeight:700,color:C.cy,marginBottom:8}}>Terminer ?</div>
        <div style={{fontSize:".82rem",color:C.txm,marginBottom:"1.2rem"}}>{ct}/39.{39-ct>0&&<> {39-ct} sans r{"\u00e9"}ponse.</>}</div>
        <div style={{display:"flex",gap:8,justifyContent:"center"}}><button style={b2} onClick={()=>setPop(false)}>Continuer</button><button style={b3} onClick={()=>{setPop(false);fin()}}>Confirmer</button></div>
      </div>
    </div>}
  </div>)}

  if(pg==="results"&&res){const nc=["#ef4444","#f97316","#f59e0b","#eab308","#84cc16","#22c55e","#10b981","#06b6d4","#3b82f6","#6366f1"];
  return(<div style={base}><div style={{display:"flex",flexDirection:"column",alignItems:"center",padding:"2.5rem 1.2rem"}}>
    <div style={{fontSize:".65rem",color:C.txd,fontFamily:"monospace",letterSpacing:".1em",marginBottom:6}}>S{"\u00c9"}RIE ECHO</div>
    <div style={{fontSize:"3.5rem",fontWeight:900,background:`linear-gradient(135deg,${C.cy},${C.ind})`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>{res.level}</div>
    <div style={{fontFamily:"monospace",fontSize:".85rem",color:C.txm,marginTop:4,marginBottom:"2rem"}}>NCLC : {res.nclc}/10</div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:8,maxWidth:560,width:"100%",marginBottom:"1.5rem"}}>
      {[["Total",res.total,39,C.cy],["A1/A2",res.a1a2,10,C.gn],["B1/B2",res.b1b2,14,C.bl],["C1/C2",res.c1c2,15,C.ind]].map(([l,v,m,c])=>(<div key={l} style={{background:C.s1,border:"1px solid rgba(0,212,255,.1)",borderRadius:8,padding:"1rem",textAlign:"center"}}><div style={{fontSize:".6rem",color:C.txd,fontFamily:"monospace",marginBottom:4}}>{l}</div><div style={{fontWeight:700,fontSize:"1.4rem",color:c}}>{v}/{m}</div><div style={{fontSize:".65rem",color:C.txd}}>{Math.round(v/m*100)}%</div></div>))}
    </div>
    {[["A1/A2",res.xp,C.gn],["B1/B2",res.yp,C.bl],["C1/C2",res.zp,C.ind]].map(([l,p,c])=>(<div key={l} style={{display:"flex",alignItems:"center",gap:8,marginBottom:8,width:"100%",maxWidth:420}}><span style={{fontFamily:"monospace",fontSize:".7rem",color:C.txd,width:42,textAlign:"right"}}>{l}</span><div style={{flex:1,height:7,background:"#121a32",borderRadius:100,overflow:"hidden"}}><div style={{height:"100%",width:`${p*100}%`,background:c,borderRadius:100}}/></div><span style={{fontFamily:"monospace",fontSize:".7rem",color:C.txm,width:32}}>{Math.round(p*100)}%</span></div>))}
    <div style={{display:"flex",gap:2,margin:"1.5rem 0",maxWidth:420,width:"100%"}}>
      {[1,2,3,4,5,6,7,8,9,10].map(n=>(<div key={n} style={{flex:1,height:28,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700,fontSize:".6rem",borderRadius:3,background:n===res.nclc?nc[n-1]:"#121a32",color:n===res.nclc?"#fff":C.txd,transform:n===res.nclc?"scaleY(1.3)":"none"}}>{n}</div>))}
    </div>
    <div style={{display:"flex",gap:8,marginTop:"1rem"}}><button style={b1} onClick={go}>RECOMMENCER</button><button style={b2} onClick={()=>nav("/")}>TOUTES LES S\u00c9RIES</button></div>
  </div></div>)}
  return null;
}
