import { useNavigate } from "react-router-dom";
import { useState, useEffect, useRef } from "react";

const DocSMS=({from,time,message})=>(<div style={{background:"#1a1a2e",borderRadius:16,padding:"1rem",maxWidth:320,border:"2px solid #2a2a4a",marginBottom:"1rem"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8,paddingBottom:6,borderBottom:"1px solid #2a2a4a"}}><span style={{fontWeight:700,fontSize:".85rem",color:"#fff"}}>{from}</span><span style={{fontSize:".7rem",color:"#888",fontFamily:"monospace"}}>{time}</span></div><div style={{background:"#0066cc",color:"#fff",padding:".6rem .9rem",borderRadius:"14px 14px 4px 14px",fontSize:".85rem",lineHeight:1.45,maxWidth:"90%"}}>{message}</div></div>);

const DocPanneau=({title,lines,icon,color})=>(<div style={{background:"#fff",color:"#222",borderRadius:8,padding:"1rem 1.2rem",maxWidth:350,borderLeft:`5px solid ${color||"#c0392b"}`,marginBottom:"1rem",boxShadow:"0 2px 8px rgba(0,0,0,.2)"}}>{icon&&<div style={{fontSize:"1.5rem",marginBottom:4}}>{icon}</div>}{title&&<div style={{color:"#fff",fontWeight:700,fontSize:".8rem",padding:".3rem .6rem",borderRadius:4,display:"inline-block",marginBottom:8,background:color||"#c0392b"}}>{title}</div>}<div style={{fontSize:".85rem",lineHeight:1.5}}>{lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>);

const DocMenu=({restaurant,items,footer})=>(<div style={{background:"#1c0a00",color:"#f0e6d3",borderRadius:10,padding:"1.2rem",maxWidth:320,marginBottom:"1rem",border:"1px solid #3a2515"}}><div style={{fontWeight:700,fontSize:".9rem",textAlign:"center",marginBottom:8,paddingBottom:8,borderBottom:"1px solid #3a2515"}}>{restaurant}</div>{items.map((it,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",fontSize:".82rem",marginBottom:3}}><span>{it.name}</span>{it.price&&<span style={{color:"#d4a574",fontFamily:"monospace",fontWeight:700}}>{it.price}</span>}</div>)}{footer&&<div style={{marginTop:8,paddingTop:8,borderTop:"1px solid #3a2515",fontSize:".75rem",textAlign:"center",color:"#a0886e"}}>{footer}</div>}</div>);

const DocBillet=({lines})=>(<div style={{background:"#f5f0e8",color:"#333",borderRadius:8,maxWidth:380,marginBottom:"1rem",overflow:"hidden",border:"1px dashed #ccc"}}><div style={{background:"#1a3a5c",color:"#fff",padding:".5rem .8rem",fontFamily:"monospace",fontSize:".75rem",fontWeight:700}}>BILLET</div><div style={{padding:".8rem",fontSize:".82rem",lineHeight:1.6}}>{lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>);

const DocLettre=({header,body,signature})=>(<div style={{background:"#fefdf8",color:"#333",borderRadius:6,padding:"1.2rem",maxWidth:500,marginBottom:"1rem",border:"1px solid #ddd",fontSize:".85rem",lineHeight:1.6}}>{header&&<div style={{fontWeight:700,fontSize:".82rem",color:"#555",marginBottom:8,paddingBottom:8,borderBottom:"1px solid #eee"}}>{header}</div>}<div style={{whiteSpace:"pre-line"}}>{body}</div>{signature&&<div style={{marginTop:"1rem",paddingTop:8,borderTop:"1px solid #eee",fontStyle:"italic",color:"#666",fontSize:".8rem",whiteSpace:"pre-line"}}>{signature}</div>}</div>);

const DocAffiche=({title,lines,color})=>(<div style={{background:"#0d1425",borderRadius:10,padding:"1.2rem",maxWidth:380,marginBottom:"1rem",border:`2px solid ${color||"#2980b9"}`,textAlign:"center"}}><div style={{fontWeight:800,fontSize:"1rem",marginBottom:8,color:color||"#2980b9"}}>{title}</div><div style={{fontSize:".85rem",lineHeight:1.5,color:"#e2e8f0"}}>{lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>);

const DocEmail=({from,to,subject,body})=>(<div style={{background:"#f8f9fa",color:"#333",borderRadius:8,padding:"1rem",maxWidth:480,marginBottom:"1rem",border:"1px solid #ddd",fontSize:".82rem",lineHeight:1.5}}><div style={{padding:"2px 0",borderBottom:"1px solid #eee"}}><b style={{color:"#666",fontSize:".75rem"}}>De :</b> {from}</div><div style={{padding:"2px 0",borderBottom:"1px solid #eee"}}><b style={{color:"#666",fontSize:".75rem"}}>{"\u00c0"} :</b> {to}</div><div style={{padding:"2px 0",borderBottom:"1px solid #eee"}}><b style={{color:"#666",fontSize:".75rem"}}>Objet :</b> <strong>{subject}</strong></div><div style={{marginTop:8,whiteSpace:"pre-line"}}>{body}</div></div>);

const DocArticle=({source,title,body})=>(<div style={{background:"#0d1425",borderRadius:8,padding:"1.2rem",maxWidth:600,marginBottom:"1rem",border:"1px solid rgba(0,212,255,.1)"}}>{source&&<div style={{fontFamily:"monospace",fontSize:".65rem",color:"#00d4ff",textTransform:"uppercase",letterSpacing:".05em",marginBottom:8}}>{source}</div>}{title&&<div style={{fontWeight:700,fontSize:".95rem",marginBottom:8,color:"#fff"}}>{title}</div>}<div style={{fontSize:".85rem",lineHeight:1.65,color:"#94a3b8"}}>{body}</div></div>);

const DocNote=({body})=>(<div style={{background:"#fff9c4",color:"#333",borderRadius:6,padding:"1rem",maxWidth:320,marginBottom:"1rem",boxShadow:"2px 2px 8px rgba(0,0,0,.15)",transform:"rotate(-1deg)",position:"relative"}}><div style={{position:"absolute",top:-8,left:"50%",transform:"translateX(-50%)",fontSize:"1.2rem"}}>{"\ud83d\udccc"}</div><div style={{fontSize:".85rem",lineHeight:1.5,whiteSpace:"pre-line",paddingTop:4}}>{body}</div></div>);

const Doc=({d})=>{if(!d)return null;const M={sms:DocSMS,panneau:DocPanneau,menu:DocMenu,billet:DocBillet,lettre:DocLettre,affiche:DocAffiche,email:DocEmail,article:DocArticle,note:DocNote};const C=M[d.type];return C?<C {...d}/>:<DocArticle body={d.body}/>};


const Q=[

    {id:1, doc:{type:"affiche",title:"MUSÉE D'ART CONTEMPORAIN",lines:["Adulte : 16 $ — Senior (65+) : 12 $","Étudiant (avec carte) : 10 $","Enfant (– de 12 ans) : GRATUIT","Mercredi soir (17h–21h) : tarif réduit 8 $"],color:"#9b59b6"}, q:"Combien paie un étudiant le mercredi à 18h ?", o:["10 $.","8 $.","12 $.","Gratuit."], c:1},
    {id:2, doc:{type:"sms",from:"Lucas",time:"12:35",message:"Rendez-vous au café Le Central à 14h, pas au Starbucks finalement. J'ai réservé la table du fond. À toute !"}, q:"Où Lucas et son ami se retrouvent-ils ?", o:["Au Starbucks.","Au café Le Central.","Chez Lucas.","Au fond du Starbucks."], c:1},
    {id:3, doc:{type:"panneau",title:"STATIONNEMENT VISITEURS",lines:["Gratuit : 2 premières heures","Au-delà : 4 $/heure","Maximum 24 heures","Véhicules d'urgence : accès prioritaire"],color:"#c0392b"}, q:"Combien paie un visiteur qui reste 4 heures ?", o:["8 $.","16 $.","Gratuit.","4 $."], c:0},
    {id:4, doc:{type:"email",from:"Clinique ophtalmologique St-Laurent",to:"j.morin@mail.ca",subject:"Rappel — Examen de la vue",body:"Bonjour M. Morin,\n\nVotre prochain examen est fixé au lundi 24 mars à 10h15. Merci d'apporter votre carte d'assurance maladie et vos lunettes actuelles. Si vous portez des lentilles, veuillez les retirer au moins 2 heures avant le rendez-vous.\n\nCordialement"}, q:"Que doit faire M. Morin s'il porte des lentilles ?", o:["Les apporter au rendez-vous.","Les retirer au moins 2 heures avant l'examen.","Les porter pendant l'examen.","Les remplacer par des lunettes la veille."], c:1},
    {id:5, doc:{type:"billet",lines:["STM — TITRE DE TRANSPORT","Pass mensuel — Mars 2026","Zone : Tous les services (bus + métro)","Non transférable","Prix : 94,00 $"]}, q:"Ce pass permet-il de prendre uniquement le métro ?", o:["Oui, le métro seulement.","Non, il couvre le bus et le métro.","Oui, mais avec un supplément bus.","Non, il couvre seulement le bus."], c:1},
    {id:6, doc:{type:"note",body:"Salut ! J'ai emprunté ta perceuse dans le garage. Je te la rends vendredi sans faute. Si tu en as besoin avant, envoie-moi un texto.\n— Benoît"}, q:"Quand Benoît rendra-t-il la perceuse ?", o:["Aujourd'hui.","Vendredi.","Quand on lui enverra un texto.","Il ne le précise pas."], c:1},
    {id:7, doc:{type:"panneau",title:"CENTRE DE TRI",lines:["Bac BLEU : papier, carton","Bac VERT : verre, métal, plastique","Bac BRUN : résidus alimentaires","⚠️ Aucun sac de plastique dans les bacs"],color:"#27ae60"}, q:"Où jeter une bouteille en plastique ?", o:["Dans le bac bleu.","Dans le bac vert.","Dans le bac brun.","Dans aucun bac (c'est interdit)."], c:1},
    {id:8, doc:{type:"affiche",title:"🎵 FESTIVAL JAZZ EN PLEIN AIR",lines:["Vendredi 20 juin — 19h à 23h","Parc des Rapides","Entrée libre — Buvette sur place","Apportez vos chaises !","⚠️ Animaux non admis"],color:"#e67e22"}, q:"Que doit-on apporter ?", o:["De la nourriture (pas de buvette).","Ses propres chaises.","Un billet d'entrée.","Son animal de compagnie."], c:1},
    {id:9, doc:{type:"sms",from:"Marie",time:"08:10",message:"Mon train a 45 min de retard 😩 Je serai au bureau vers 10h15 au lieu de 9h30. Peux-tu prévenir Nathalie que je serai en retard à la réunion de 10h ?"}, q:"À quelle heure Marie devait-elle arriver initialement ?", o:["À 9h30.","À 10h15.","À 10h.","À 8h10."], c:0},
    {id:10, doc:{type:"panneau",lines:["PHARMACIE DE GARDE","Ce week-end :","Pharmacie Nguyen — 220 rue Beaubien","Samedi : 9h – 18h","Dimanche : 10h – 16h"],icon:"💊",color:"#e91e63"}, q:"Peut-on aller à cette pharmacie le dimanche à 17h ?", o:["Oui, elle est ouverte jusqu'à 18h le dimanche.","Non, elle ferme à 16h le dimanche.","Oui, c'est une pharmacie de garde.","Non, elle est fermée tout le dimanche."], c:1},
    // B1/B2
    {id:11, doc:{type:"article",source:"Le Devoir — Technologie",body:"L'application de réalité augmentée développée par le Musée de la civilisation de Québec permet aux visiteurs de « voir » les bâtiments historiques tels qu'ils étaient au XVIIᵉ siècle. L'app a été téléchargée 45 000 fois. Toutefois, 60 % des utilisateurs l'ont désinstallée après une seule utilisation, jugeant l'expérience trop lente et la reconnaissance des lieux imprécise."}, q:"Pourquoi l'application n'a-t-elle pas convaincu la majorité des utilisateurs ?", o:["Le contenu historique était inexact.","L'expérience était jugée trop lente et imprécise.","L'application était payante.","Les visiteurs préfèrent les guides humains."], c:1},
    {id:12, doc:{type:"article",source:"Radio-Canada — Santé",body:"Le Québec manque cruellement de médecins de famille : 1,2 million de personnes n'en ont pas. Le gouvernement a autorisé les infirmières praticiennes spécialisées (IPS) à poser des diagnostics et prescrire des médicaments pour des conditions courantes. L'Ordre des médecins soutient cette mesure mais demande que les IPS ne traitent que des cas « simples » — une restriction que les infirmières jugent paternaliste."}, q:"Quel désaccord oppose les médecins et les infirmières ?", o:["Les médecins refusent que les infirmières prescrivent.","Les médecins veulent limiter les IPS aux cas simples, ce que les infirmières contestent.","Les infirmières demandent un salaire égal aux médecins.","Les médecins veulent supprimer le rôle des IPS."], c:1},
    {id:13, doc:{type:"article",source:"La Presse — Énergie",body:"Hydro-Québec exporte de l'électricité vers New York et le Massachusetts, mais un paradoxe émerge : certaines communautés autochtones situées près des barrages n'ont pas accès à un réseau électrique fiable et dépendent encore de génératrices au diesel. L'ironie d'exporter de l'énergie propre tout en privant ses propres citoyens d'accès à cette énergie n'échappe à personne."}, q:"Quel paradoxe l'article soulève-t-il ?", o:["Hydro-Québec vend de l'électricité trop chère aux Américains.","Le Québec exporte de l'énergie propre alors que des communautés locales n'y ont pas accès.","Les barrages hydroélectriques causent plus de pollution que le diesel.","Les États américains refusent d'acheter l'électricité québécoise."], c:1},
    {id:14, doc:{type:"article",source:"Le Soleil — Immigration",body:"Le programme des travailleurs étrangers temporaires (PTET) est critiqué de tous côtés. Les syndicats dénoncent une main-d'œuvre captive et vulnérable aux abus. Les employeurs trouvent les procédures trop lourdes. Les travailleurs eux-mêmes acceptent des conditions dégradantes par peur de perdre leur permis, lié à un employeur spécifique."}, q:"Pourquoi les travailleurs étrangers acceptent-ils de mauvaises conditions ?", o:["Parce qu'ils ne connaissent pas leurs droits.","Parce que leur permis est lié à un employeur, ce qui les rend vulnérables.","Parce que les conditions sont meilleures qu'au pays.","Parce que les syndicats refusent de les représenter."], c:1},
    {id:15, doc:{type:"article",source:"Radio-Canada — Environnement",body:"La consigne élargie, qui inclut désormais les bouteilles de vin et de spiritueux au Québec, a généré un taux de retour de 82 % la première année — bien au-delà des 60 % espérés. Cependant, les restaurateurs se plaignent du manque d'espace de stockage pour les bouteilles vides et du coût logistique non compensé."}, q:"Quel problème les restaurateurs rencontrent-ils ?", o:["Les clients refusent de payer la consigne.","Le stockage des bouteilles vides et les coûts logistiques.","Le taux de retour est trop faible.","La qualité du vin consigné est moindre."], c:1},
    {id:16, doc:{type:"article",source:"Le Devoir — Éducation",body:"Le ministre de l'Éducation a annoncé l'embauche de 500 psychologues scolaires supplémentaires. Les syndicats saluent l'initiative mais soulignent un problème : il n'y a que 180 psychologues disponibles sur le marché du travail. « On ne peut pas embaucher des gens qui n'existent pas », résume une porte-parole syndicale."}, q:"Pourquoi l'annonce du ministre pose-t-elle problème ?", o:["Les psychologues scolaires sont trop coûteux.","Il n'y a pas assez de psychologues disponibles pour combler les 500 postes.","Les syndicats refusent les embauches.","Les psychologues ne veulent pas travailler en milieu scolaire."], c:1},
    {id:17, doc:{type:"article",source:"La Presse — Société",body:"Le Québec a adopté une loi autorisant l'aide médicale à mourir pour les personnes atteintes de maladies mentales, sous conditions strictes. Les psychiatres sont profondément divisés : certains y voient un droit fondamental du patient, d'autres estiment qu'il est impossible de déterminer le caractère « irrémédiable » d'une maladie mentale, dont l'évolution est par nature imprévisible."}, q:"Quelle est l'objection principale des psychiatres opposés à cette loi ?", o:["La loi est inconstitutionnelle.","L'évolution imprévisible des maladies mentales rend le critère d'irrémédiabilité impossible à appliquer.","Il n'existe pas de maladie mentale irrémédiable.","Les patients ne sont pas en mesure de consentir."], c:1},
    {id:18, doc:{type:"article",source:"Le Journal de Montréal",body:"Airbnb a accepté de percevoir la taxe de séjour pour le compte des municipalités québécoises. Les hôteliers ne sont pas satisfaits : ils réclament aussi un plafond sur le nombre de nuits qu'un logement peut être loué par an (120 jours maximum), comme c'est le cas à Paris et Amsterdam."}, q:"Que réclament les hôteliers en plus de la taxe de séjour ?", o:["L'interdiction totale d'Airbnb.","Un plafond sur le nombre de nuits de location par an.","Une taxe plus élevée pour Airbnb.","Le droit de publier leurs propres offres sur Airbnb."], c:1},
    {id:19, doc:{type:"article",source:"Québec Science — Climat",body:"L'érosion côtière menace 5 000 bâtiments le long du fleuve Saint-Laurent. Le gouvernement offre deux options aux propriétaires : une aide pour renforcer les berges OU un rachat du terrain au prix du marché. La majorité choisit le renforcement, mais les experts préviennent que cette solution est temporaire : avec la montée des eaux, ces terrains seront inhabitables d'ici 30 ans."}, q:"Pourquoi les experts recommandent-ils plutôt le rachat ?", o:["Parce que le renforcement est plus coûteux.","Parce que le renforcement n'est qu'une solution temporaire face à la montée des eaux.","Parce que les propriétaires refusent de quitter leur maison.","Parce que le rachat permettrait de construire des digues."], c:1},
    {id:20, doc:{type:"article",source:"Le Devoir — Culture",body:"Netflix a supprimé le partage de compte au Canada. Les abonnés qui le pratiquaient (estimés à 30 %) ont eu trois réactions : un tiers a pris son propre abonnement, un tiers est passé à des concurrents moins chers, et un tiers a annulé tout abonnement de streaming. Netflix a donc gagné des abonnés individuels mais perdu un quart de sa base totale d'utilisateurs."}, q:"Quel a été l'impact net pour Netflix ?", o:["Un gain massif d'abonnés.","Plus d'abonnés payants mais moins d'utilisateurs au total.","Aucun changement significatif.","Une perte totale d'abonnés et d'utilisateurs."], c:1},
    {id:21, doc:{type:"article",source:"Radio-Canada — Autochtones",body:"Le Conseil des Innus de Pessamit a inauguré sa propre école secondaire, entièrement en langue innue pour les trois premières années. Le français est enseigné comme langue seconde à partir de la 4ᵉ année. Le ministère a d'abord refusé de reconnaître le diplôme, avant de reculer sous la pression médiatique."}, q:"Quelle difficulté cette école a-t-elle rencontrée ?", o:["Les élèves refusaient d'apprendre le français.","Le ministère a initialement refusé de reconnaître le diplôme.","Les enseignants ne maîtrisaient pas la langue innue.","Les parents préféraient l'école française."], c:1},
    {id:22, doc:{type:"article",source:"La Presse — Numérique",body:"La Ville de Québec a installé 200 capteurs de qualité de l'air dans ses rues. Les données sont accessibles en temps réel sur une application. Paradoxalement, les quartiers les plus pollués sont aussi ceux où les résidents consultent le moins l'application — soit par manque d'accès numérique, soit par une résignation liée à des décennies de promesses non tenues."}, q:"Pourquoi les résidents des quartiers les plus pollués n'utilisent-ils pas l'application ?", o:["L'application est trop compliquée.","Par manque d'accès numérique ou par résignation face aux promesses non tenues.","Ils ne sont pas informés de l'existence de l'application.","La qualité de l'air est bonne dans ces quartiers."], c:1},
    {id:23, doc:{type:"article",source:"Le Devoir — Immobilier",body:"Montréal a adopté un règlement imposant 20 % de logements abordables dans tout nouveau projet de plus de 50 unités. Les promoteurs immobiliers menacent de se tourner vers les banlieues, où ce règlement ne s'applique pas. Les urbanistes craignent un effet pervers : l'étalement urbain, qui augmenterait la dépendance à l'automobile et les émissions de GES."}, q:"Quel effet pervers les urbanistes redoutent-ils ?", o:["La hausse des prix dans les banlieues.","L'étalement urbain causé par la fuite des promoteurs vers les banlieues.","La construction de logements de mauvaise qualité.","L'abandon complet des projets immobiliers."], c:1},
    {id:24, doc:{type:"article",source:"Le Soleil — Économie",body:"Le port de Montréal a enregistré une baisse de 15 % du trafic de conteneurs, en partie à cause de la concurrence du port de Halifax, accessible à l'année sans brise-glace. La Voie maritime du Saint-Laurent, fermée quatre mois par an en raison des glaces, constitue un désavantage structurel que le réchauffement climatique pourrait paradoxalement réduire."}, q:"Pourquoi le réchauffement climatique pourrait-il avantager le port de Montréal ?", o:["Il attirerait plus de touristes.","Il réduirait la période de fermeture hivernale de la Voie maritime.","Il augmenterait le prix des conteneurs à Halifax.","Il rendrait le brise-glace moins coûteux."], c:1},
    // C1/C2
    {id:25, doc:{type:"article",source:"Essai — Méritocratie",body:"La méritocratie ne se contente pas de légitimer les inégalités — elle les naturalise. En transformant un résultat social (la réussite ou l'échec) en verdict moral (le mérite ou l'indignité), elle rend les privilégiés aveugles à leurs avantages et les défavorisés honteux de leur condition. Le plus grand tort de la méritocratie n'est pas de récompenser le talent, mais de punir le manque de chance."}, q:"Quel est le « plus grand tort » de la méritocratie selon l'auteur ?", o:["De récompenser les plus talentueux.","De transformer le manque de chance en faute morale.","De favoriser la compétition entre les individus.","D'ignorer le rôle de l'effort personnel."], c:1},
    {id:26, doc:{type:"text",body:"Montréal, vue d'en haut, ressemblait à une phrase inachevée. Les rues traçaient des lignes qui ne menaient nulle part de précis, les parcs ouvraient des parenthèses que personne ne refermait, et le fleuve, ce point-virgule géant, séparait deux pensées qui n'avaient jamais appris à se comprendre. C'était une ville qui se lisait comme un brouillon — raturée, imparfaite, mais vivante de l'énergie des choses qui n'ont pas renoncé à chercher leur forme."}, q:"Comment le narrateur qualifie-t-il Montréal ?", o:["Comme une ville achevée et harmonieuse.","Comme un brouillon vivant, imparfait mais plein d'énergie.","Comme une ville en déclin qui a perdu son identité.","Comme une métropole trop grande et désorganisée."], c:1},
    {id:27, doc:{type:"article",source:"Éthique de l'IA",body:"L'IA générative ne fait pas que reproduire : elle transforme notre rapport à la création. Quand un outil génère un texte en secondes, la question n'est plus « peut-on créer sans effort ? » mais « que perd-on quand l'effort disparaît ? ». La valeur d'une œuvre réside peut-être moins dans son résultat que dans le processus de création — la lenteur, les hésitations, les choix assumés."}, q:"Quelle perte l'auteur associe-t-il à l'IA créative ?", o:["La disparition des emplois artistiques.","La perte du processus créatif lui-même, fait de lenteur et de choix.","La diminution de la qualité esthétique des œuvres.","L'incapacité des machines à comprendre les émotions humaines."], c:1},
    {id:28, doc:{type:"article",source:"Psychologie sociale",body:"La « fatigue compassionnelle » ne touche pas que les soignants — elle affecte quiconque est exposé de manière continue à la souffrance d'autrui. Le paradoxe est cruel : c'est précisément les personnes les plus empathiques qui y sont les plus vulnérables. L'empathie, cette qualité célébrée comme une vertu, devient alors l'instrument de sa propre destruction."}, q:"Pourquoi le paradoxe de la fatigue compassionnelle est-il qualifié de « cruel » ?", o:["Parce qu'il touche les personnes les moins empathiques.","Parce que c'est l'empathie elle-même qui rend vulnérable à la fatigue.","Parce que les soignants ne bénéficient d'aucun soutien.","Parce que la fatigue compassionnelle est incurable."], c:1},
    {id:29, doc:{type:"article",source:"Droit — Secret des sources",body:"La protection des sources journalistiques est un pilier de la liberté de presse. Mais cette protection entre en collision avec le droit pénal lorsqu'un journaliste détient des informations sur un crime imminent. Le refus de témoigner, légitime pour protéger une source, devient problématique quand des vies sont en jeu. Aucune démocratie n'a trouvé de solution satisfaisante à ce dilemme."}, q:"Quel dilemme l'auteur décrit-il ?", o:["Entre la liberté de presse et les intérêts commerciaux des médias.","Entre la protection des sources et l'obligation de prévenir un crime imminent.","Entre le journalisme d'investigation et le journalisme d'opinion.","Entre le droit à l'information et la vie privée des citoyens."], c:1},
    {id:30, doc:{type:"article",source:"Philosophie du langage",body:"Traduire, c'est trahir — mais ne pas traduire, c'est enfermer. Le traducteur navigue entre l'impossible fidélité au texte original et l'indispensable accessibilité au lecteur. Chaque choix est une perte : garder un jeu de mots, c'est sacrifier le sens ; garder le sens, c'est perdre la musique. La traduction parfaite est celle qui rend visible sa propre imperfection."}, q:"Que signifie « la traduction parfaite rend visible sa propre imperfection » ?", o:["Qu'une bonne traduction contient volontairement des erreurs.","Qu'elle reconnaît honnêtement qu'elle ne peut pas tout transmettre de l'original.","Que les traducteurs sont toujours insatisfaits de leur travail.","Que la perfection en traduction est un objectif facilement atteignable."], c:1},
    {id:31, doc:{type:"article",source:"Neurosciences",body:"La perception n'est pas un miroir — c'est une interprétation. Notre cerveau construit une version simplifiée et fonctionnelle de la réalité, comblant les lacunes avec des inférences. La « cécité au changement » le prouve : nous ne remarquons pas des modifications majeures dans notre champ visuel quand notre attention est détournée. Nous vivons, littéralement, dans un monde que notre cerveau invente."}, q:"Que démontre la « cécité au changement » selon l'auteur ?", o:["Que notre mémoire est défaillante.","Que notre perception est une construction du cerveau, pas un reflet fidèle.","Que nous sommes naturellement distraits.","Que notre vision se dégrade avec l'âge."], c:1},
    {id:32, doc:{type:"article",source:"Épistémologie",body:"La crise de la reproductibilité en science n'est pas un accident — elle est le symptôme d'un système malade. La pression à publier pousse les chercheurs à « p-hacker » : torturer les données jusqu'à obtenir un résultat significatif. Les revues préfèrent les résultats positifs et spectaculaires, créant un biais de publication qui fausse l'état des connaissances."}, q:"Quelle est la cause systémique de la crise de la reproductibilité ?", o:["L'incompétence des chercheurs.","La pression à publier des résultats positifs, qui encourage des pratiques biaisées.","Le manque de financement de la recherche fondamentale.","L'incapacité des logiciels statistiques à produire des résultats fiables."], c:1},
    {id:33, doc:{type:"article",source:"Essai — Architecture",body:"L'habitat vernaculaire — maisons de terre, igloos, cases sur pilotis — n'a pas d'architecte, mais il a une intelligence. Fruit de siècles d'observation, il s'adapte au climat, aux matériaux disponibles et aux modes de vie locaux avec une précision que l'architecture savante peine à égaler. Le paradoxe de la modernité est d'avoir méprisé ce savoir au moment précis où la crise climatique nous obligeait à le redécouvrir."}, q:"Quel paradoxe la modernité a-t-elle produit selon l'auteur ?", o:["L'architecture moderne est plus durable que l'habitat vernaculaire.","Elle a méprisé un savoir adaptatif au moment où elle en avait le plus besoin.","Les architectes modernes s'inspirent trop de l'habitat vernaculaire.","L'habitat vernaculaire est incompatible avec la vie contemporaine."], c:1},
    {id:34, doc:{type:"article",source:"Politique — Commémoration",body:"Toute commémoration est un acte de sélection. En choisissant ce qu'on célèbre, on choisit aussi ce qu'on efface. Les « guerres mémorielles » autour des statues ne portent pas vraiment sur le passé : elles portent sur le présent — sur qui a le pouvoir de définir le récit dans lequel une société se reconnaît."}, q:"Selon l'auteur, que révèlent les débats sur les statues ?", o:["Un intérêt grandissant pour l'histoire.","Des luttes de pouvoir actuelles sur le récit collectif.","Le vandalisme comme forme d'expression politique.","La volonté de détruire tout lien avec le passé."], c:1},
    {id:35, doc:{type:"article",source:"Post-vérité — Essai",body:"Le problème de la post-vérité n'est pas que les gens mentent — on a toujours menti. C'est que la distinction entre fait et opinion est devenue elle-même objet de contestation. Quand un politique dit « c'est votre vérité, pas la mienne », il ne relativise pas un point de vue — il abolit le terrain commun sur lequel un désaccord productif pourrait avoir lieu."}, q:"Qu'est-ce qui est réellement en jeu dans la post-vérité selon l'auteur ?", o:["La prolifération des fausses informations sur Internet.","L'abolition du terrain commun qui permet le désaccord productif.","Le manque d'éducation aux médias dans les écoles.","La censure des opinions dissidentes par les plateformes."], c:1},
    {id:36, doc:{type:"text",body:"Quand les premières voiles apparurent à l'horizon, les anciens ne paniquèrent pas. Des générations d'alliances et de migrations leur avaient appris l'art de la transformation. Ce qui les inquiéta, ce ne fut pas l'inconnu — mais la rigidité. Quelque chose dans la géométrie de ces navires, dans leur avancée rectiligne, annonçait un monde qui ne négocierait pas."}, q:"Que perçoivent les anciens dans les navires ?", o:["Une menace militaire imminente.","Un ordre nouveau qui ne fera pas de place à la négociation.","Une opportunité commerciale.","Un phénomène naturel inhabituel."], c:1},
    {id:37, doc:{type:"article",source:"Démocratie numérique",body:"Les plateformes de participation citoyenne en ligne attirent un profil très homogène : urbains, diplômés, déjà politisés. Résultat paradoxal : un outil conçu pour démocratiser la parole finit par amplifier la voix de ceux qui n'en avaient pas besoin, et par rendre encore plus invisibles ceux qu'il prétendait inclure."}, q:"Quel est le paradoxe des plateformes de participation citoyenne ?", o:["Elles sont trop coûteuses pour les municipalités.","Elles amplifient la voix de ceux qui étaient déjà entendus et marginalisent les autres.","Elles remplacent le vote traditionnel.","Elles sont piratées par des groupes d'intérêt."], c:1},
    {id:38, doc:{type:"article",source:"Bioéthique — CRISPR",body:"CRISPR ouvre la possibilité d'éradiquer des maladies héréditaires — mais aussi de « choisir » les caractéristiques de ses enfants. Le glissement du thérapeutique vers l'amélioratif pose une question vertigineuse : qui décidera de ce qu'est un « bon » génome ? Si c'est le marché, les enfants « améliorés » seront ceux dont les parents ont les moyens. L'eugénisme du XXIᵉ siècle pourrait avoir un visage libéral."}, q:"Quel risque l'auteur associe-t-il à CRISPR ?", o:["Que la technologie ne fonctionne pas.","Qu'un eugénisme de marché creuse les inégalités.","Que les maladies génétiques ne soient jamais éradiquées.","Que les scientifiques perdent le contrôle de la technologie."], c:1},
    {id:39, doc:{type:"article",source:"Philosophie morale",body:"Le dilemme du tramway, souvent invoqué en éthique de l'IA, présente une faiblesse fondamentale : il réduit la morale à un calcul binaire. Dans la vie réelle, les choix moraux ne se présentent jamais sous la forme de deux options pures. Ils sont tissés de zones grises, d'informations incomplètes et de conséquences imprévisibles. L'éthique n'est pas un algorithme — c'est un art du jugement en situation d'incertitude."}, q:"Pourquoi l'auteur juge-t-il le dilemme du tramway inadéquat pour penser l'éthique de l'IA ?", o:["Parce qu'il est trop vieux pour être pertinent.","Parce qu'il simplifie la réalité morale en ignorant l'incertitude et la complexité.","Parce que les voitures autonomes ne circulent pas sur des rails.","Parce qu'il favorise une approche utilitariste de la morale."], c:1},
];

function sc(a){let x=0,y=0,z=0;Q.forEach((q,i)=>{const ok=a[i]===q.c;if(i<10&&ok)x++;else if(i<24&&ok)y++;else if(i>=24&&ok)z++});const xp=x/10,yp=y/14,zp=z/15,t=x+y+z,tp=t/39;let n;if(zp>=.8&&yp>=.7)n=tp>=.85?10:tp>=.75?9:8;else if(zp>=.5&&yp>=.6)n=tp>=.65?7:6;else if(yp>=.5&&xp>=.7)n=tp>=.55?6:5;else if(xp>=.7&&yp>=.3)n=4;else if(xp>=.5)n=3;else n=2;const lv=n>=9?"C2":n>=7?"C1":n>=6?"B2":n>=4?"B1":n>=3?"A2":"A1";return{nclc:n,level:lv,total:t,a1a2:x,b1b2:y,c1c2:z,xp,yp,zp}}

const C={bg:"#080c16",s1:"#0d1425",cy:"#00d4ff",ind:"#6366f1",gn:"#10b981",bl:"#3b82f6",rd:"#ef4444",am:"#f59e0b",tx:"#e2e8f0",txm:"#94a3b8",txd:"#64748b"};
const base={fontFamily:"system-ui,sans-serif",background:C.bg,color:C.tx,minHeight:"100vh"};
const b1={fontWeight:700,fontSize:".85rem",letterSpacing:".08em",textTransform:"uppercase",background:`linear-gradient(135deg,${C.cy},${C.ind})`,color:"#fff",border:"none",padding:".9rem 2.5rem",borderRadius:8,cursor:"pointer"};
const b2={fontSize:".8rem",background:"transparent",color:C.txm,border:"1px solid rgba(0,212,255,.15)",padding:".6rem 1.2rem",borderRadius:6,cursor:"pointer",fontFamily:"inherit"};
const b3={...b1,fontSize:".75rem",padding:".6rem 1.2rem",background:`linear-gradient(135deg,${C.gn},#059669)`};

export default function App(){
  const nav=useNavigate();
  const[pg,setPg]=useState("home");
  const[ci,setCi]=useState(0);
  const[ans,setAns]=useState({});
  const[sec,setSec]=useState(3600);
  const[on,setOn]=useState(false);
  const[pop,setPop]=useState(false);
  const[fl,setFl]=useState(new Set());
  const[nv,setNv]=useState(false);
  const[res,setRes]=useState(null);
  const tr=useRef(null);

  useEffect(()=>{if(!on)return;tr.current=setInterval(()=>setSec(p=>{if(p<=1){clearInterval(tr.current);return 0}return p-1}),1000);return()=>clearInterval(tr.current)},[on]);
  useEffect(()=>{if(sec===0&&on){setOn(false);setRes(sc(ans));setPg("results")}},[sec,on,ans]);

  const go=()=>{setAns({});setCi(0);setSec(3600);setOn(true);setFl(new Set());setNv(false);setPg("quiz")};
  const fin=()=>{setOn(false);clearInterval(tr.current);setRes(sc(ans));setPg("results")};
  const pk=(i,j)=>setAns(p=>({...p,[i]:j}));
  const fg=i=>{setFl(p=>{const n=new Set(p);n.has(i)?n.delete(i):n.add(i);return n})};
  const fm=s=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;
  const ct=Object.keys(ans).length;
  const L=["A","B","C","D"];

  if(pg==="home")return(
    <div style={base}><div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",minHeight:"100vh",padding:"2rem",textAlign:"center"}}>
      <div style={{fontSize:".65rem",color:C.cy,letterSpacing:".15em",textTransform:"uppercase",marginBottom:"2rem",fontFamily:"monospace"}}>FLAB GAMES</div>
      <h1 style={{fontSize:"clamp(2rem,7vw,3.5rem)",fontWeight:900,background:`linear-gradient(135deg,#fff,${C.cy},${C.ind})`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",lineHeight:1,marginBottom:8}}>ESCAPE LAB</h1>
      <p style={{fontSize:"clamp(.75rem,2vw,1rem)",color:C.txm,letterSpacing:".15em",textTransform:"uppercase",marginBottom:"1.5rem"}}>S{"\u00e9"}rie Charlie {"\u2014"} TCF Canada</p>
      <p style={{fontSize:".9rem",color:C.txd,maxWidth:460,lineHeight:1.6,marginBottom:"2.5rem"}}>39 questions avec vrais pi{"\u00e8"}ges. 60 minutes. A1{"\u2192"}C2.</p>
      <button style={b1} onClick={go}>COMMENCER</button>
      <div style={{display:"flex",gap:"2rem",marginTop:"2.5rem",flexWrap:"wrap",justifyContent:"center"}}>
        {[["39","Questions"],["60","Min"],["NCLC","Score"]].map(([v,l])=>(<div key={l} style={{textAlign:"center"}}><div style={{fontWeight:700,fontSize:"1.3rem",color:C.cy}}>{v}</div><div style={{fontSize:".6rem",color:C.txd,textTransform:"uppercase"}}>{l}</div></div>))}
      </div>
    </div></div>
  );

  if(pg==="quiz"){const q=Q[ci],ll=ci<10?"A1/A2":ci<24?"B1/B2":"C1/C2",lc=ci<10?C.gn:ci<24?C.bl:C.ind,tc=sec<=300?C.rd:sec<=900?C.am:C.cy;
  return(<div style={base}>
    <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:".6rem 1rem",background:C.s1,borderBottom:"1px solid rgba(0,212,255,.1)",position:"sticky",top:0,zIndex:50,flexWrap:"wrap",gap:4}}>
      <span style={{fontWeight:700,fontSize:".75rem",color:C.cy}}>ESCAPE LAB</span>
      <div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontWeight:700,fontSize:"1.1rem",color:tc,fontFamily:"monospace"}}>{fm(sec)}</span><span style={{fontSize:".65rem",color:C.txd,fontFamily:"monospace"}}>{ct}/39</span></div>
      <div style={{display:"flex",gap:4}}>
        <button onClick={()=>fg(ci)} style={{...b2,padding:"4px 8px",borderColor:fl.has(ci)?C.ind:"rgba(0,212,255,.15)",color:fl.has(ci)?C.ind:C.txm}}>{"\u2691"}</button>
        <button onClick={()=>setNv(!nv)} style={{...b2,padding:"4px 8px"}}>{"\u2630"}</button>
      </div>
    </div>
    <div style={{height:3,background:"#121a32"}}><div style={{height:"100%",width:`${(ct/39)*100}%`,background:`linear-gradient(90deg,${C.cy},${C.ind})`,transition:"width .3s"}}/></div>
    <div style={{maxWidth:780,margin:"0 auto",padding:"1.5rem 1rem",display:"flex",flexDirection:"column",minHeight:"calc(100vh - 60px)"}}>
      <span style={{display:"inline-block",padding:"3px 10px",borderRadius:100,fontSize:".6rem",fontWeight:700,marginBottom:12,border:`1px solid ${lc}33`,color:lc,background:`${lc}11`,alignSelf:"flex-start"}}>Q{ci+1} {"\u00b7"} {ll}</span>
      <Doc d={q.doc}/>
      <p style={{fontWeight:600,fontSize:".95rem",marginBottom:12,color:"#fff"}}>{q.q}</p>
      <div style={{display:"flex",flexDirection:"column",gap:8,marginBottom:"1.5rem"}}>
        {q.o.map((o,i)=>(<button key={i} onClick={()=>pk(ci,i)} style={{display:"flex",alignItems:"flex-start",gap:10,padding:".8rem 1rem",background:ans[ci]===i?"rgba(0,212,255,.06)":C.s1,border:`1px solid ${ans[ci]===i?C.cy:"rgba(0,212,255,.1)"}`,borderRadius:8,cursor:"pointer",textAlign:"left",fontFamily:"inherit",fontSize:".85rem",color:C.tx,lineHeight:1.45,transition:"all .15s"}}>
          <span style={{flexShrink:0,width:26,height:26,borderRadius:5,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"monospace",fontWeight:700,fontSize:".7rem",background:ans[ci]===i?C.cy:"#121a32",color:ans[ci]===i?C.bg:C.txd}}>{L[i]}</span>
          <span>{o}</span>
        </button>))}
      </div>
      <div style={{display:"flex",justifyContent:"space-between",marginTop:"auto",paddingTop:"1rem",gap:8}}>
        <button style={{...b2,opacity:ci===0?.3:1}} onClick={()=>setCi(Math.max(0,ci-1))} disabled={ci===0}>{"\u2190"} Pr{"\u00e9"}c.</button>
        {ci<38?<button style={b2} onClick={()=>setCi(ci+1)}>Suiv. {"\u2192"}</button>:<button style={b3} onClick={()=>setPop(true)}>TERMINER</button>}
      </div>
    </div>
    {nv&&<div onClick={e=>{if(e.target===e.currentTarget)setNv(false)}} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.6)",zIndex:100,display:"flex",justifyContent:"flex-end"}}>
      <div style={{width:"min(360px,88vw)",background:C.s1,padding:"1.2rem",overflowY:"auto",borderLeft:"1px solid rgba(0,212,255,.1)"}}>
        <div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><span style={{fontWeight:700,fontSize:".8rem",color:C.cy}}>NAVIGATION</span><button style={{...b2,padding:"2px 8px"}} onClick={()=>setNv(false)}>{"\u2715"}</button></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(38px,1fr))",gap:5,marginBottom:12}}>
          {Q.map((_,i)=>(<div key={i} onClick={()=>{setCi(i);setNv(false)}} style={{aspectRatio:"1",borderRadius:5,border:`1px solid ${i===ci?C.cy:ans[i]!=null?C.cy+"40":"rgba(0,212,255,.1)"}`,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"monospace",fontSize:".65rem",fontWeight:700,cursor:"pointer",background:ans[i]!=null?C.cy+"1a":"#121a32",color:ans[i]!=null?C.cy:C.txd,boxShadow:i===ci?`0 0 8px ${C.cy}40`:"none",position:"relative"}}>{i+1}{fl.has(i)&&<span style={{position:"absolute",top:-2,right:1,fontSize:".5rem",color:C.am}}>{"\u2691"}</span>}</div>))}
        </div>
        <button style={{...b3,width:"100%"}} onClick={()=>{setNv(false);setPop(true)}}>TERMINER</button>
      </div>
    </div>}
    {pop&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.7)",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",padding:"1rem"}}>
      <div style={{background:C.s1,border:"1px solid rgba(0,212,255,.1)",borderRadius:14,padding:"1.8rem",maxWidth:400,width:"100%",textAlign:"center"}}>
        <div style={{fontSize:"2rem",marginBottom:8}}>{"\u26a0\ufe0f"}</div>
        <div style={{fontWeight:700,color:C.cy,marginBottom:8}}>Terminer ?</div>
        <div style={{fontSize:".82rem",color:C.txm,marginBottom:"1.2rem"}}>{ct}/39.{39-ct>0&&<> {39-ct} sans r{"\u00e9"}ponse.</>}</div>
        <div style={{display:"flex",gap:8,justifyContent:"center"}}><button style={b2} onClick={()=>setPop(false)}>Continuer</button><button style={b3} onClick={()=>{setPop(false);fin()}}>Confirmer</button></div>
      </div>
    </div>}
  </div>)}

  if(pg==="results"&&res){const nc=["#ef4444","#f97316","#f59e0b","#eab308","#84cc16","#22c55e","#10b981","#06b6d4","#3b82f6","#6366f1"];
  return(<div style={base}><div style={{display:"flex",flexDirection:"column",alignItems:"center",padding:"2.5rem 1.2rem"}}>
    <div style={{fontSize:".65rem",color:C.txd,fontFamily:"monospace",letterSpacing:".1em",marginBottom:6}}>S{"\u00c9"}RIE CHARLIE</div>
    <div style={{fontSize:"3.5rem",fontWeight:900,background:`linear-gradient(135deg,${C.cy},${C.ind})`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>{res.level}</div>
    <div style={{fontFamily:"monospace",fontSize:".85rem",color:C.txm,marginTop:4,marginBottom:"2rem"}}>NCLC : {res.nclc}/10</div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:8,maxWidth:560,width:"100%",marginBottom:"1.5rem"}}>
      {[["Total",res.total,39,C.cy],["A1/A2",res.a1a2,10,C.gn],["B1/B2",res.b1b2,14,C.bl],["C1/C2",res.c1c2,15,C.ind]].map(([l,v,m,c])=>(<div key={l} style={{background:C.s1,border:"1px solid rgba(0,212,255,.1)",borderRadius:8,padding:"1rem",textAlign:"center"}}><div style={{fontSize:".6rem",color:C.txd,fontFamily:"monospace",marginBottom:4}}>{l}</div><div style={{fontWeight:700,fontSize:"1.4rem",color:c}}>{v}/{m}</div><div style={{fontSize:".65rem",color:C.txd}}>{Math.round(v/m*100)}%</div></div>))}
    </div>
    {[["A1/A2",res.xp,C.gn],["B1/B2",res.yp,C.bl],["C1/C2",res.zp,C.ind]].map(([l,p,c])=>(<div key={l} style={{display:"flex",alignItems:"center",gap:8,marginBottom:8,width:"100%",maxWidth:420}}><span style={{fontFamily:"monospace",fontSize:".7rem",color:C.txd,width:42,textAlign:"right"}}>{l}</span><div style={{flex:1,height:7,background:"#121a32",borderRadius:100,overflow:"hidden"}}><div style={{height:"100%",width:`${p*100}%`,background:c,borderRadius:100}}/></div><span style={{fontFamily:"monospace",fontSize:".7rem",color:C.txm,width:32}}>{Math.round(p*100)}%</span></div>))}
    <div style={{display:"flex",gap:2,margin:"1.5rem 0",maxWidth:420,width:"100%"}}>
      {[1,2,3,4,5,6,7,8,9,10].map(n=>(<div key={n} style={{flex:1,height:28,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700,fontSize:".6rem",borderRadius:3,background:n===res.nclc?nc[n-1]:"#121a32",color:n===res.nclc?"#fff":C.txd,transform:n===res.nclc?"scaleY(1.3)":"none"}}>{n}</div>))}
    </div>
    <div style={{display:"flex",gap:8,marginTop:"1rem"}}><button style={b1} onClick={go}>RECOMMENCER</button><button style={b2} onClick={()=>nav("/")}>TOUTES LES S\u00c9RIES</button></div>
  </div></div>)}
  return null;
}
