import { useNavigate } from "react-router-dom";
import { useState, useEffect, useRef } from "react";

const DocSMS=({from,time,message})=>(<div style={{background:"#1a1a2e",borderRadius:16,padding:"1rem",maxWidth:320,border:"2px solid #2a2a4a",marginBottom:"1rem"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8,paddingBottom:6,borderBottom:"1px solid #2a2a4a"}}><span style={{fontWeight:700,fontSize:".85rem",color:"#fff"}}>{from}</span><span style={{fontSize:".7rem",color:"#888",fontFamily:"monospace"}}>{time}</span></div><div style={{background:"#0066cc",color:"#fff",padding:".6rem .9rem",borderRadius:"14px 14px 4px 14px",fontSize:".85rem",lineHeight:1.45,maxWidth:"90%"}}>{message}</div></div>);

const DocPanneau=({title,lines,icon,color})=>(<div style={{background:"#fff",color:"#222",borderRadius:8,padding:"1rem 1.2rem",maxWidth:350,borderLeft:`5px solid ${color||"#c0392b"}`,marginBottom:"1rem",boxShadow:"0 2px 8px rgba(0,0,0,.2)"}}>{icon&&<div style={{fontSize:"1.5rem",marginBottom:4}}>{icon}</div>}{title&&<div style={{color:"#fff",fontWeight:700,fontSize:".8rem",padding:".3rem .6rem",borderRadius:4,display:"inline-block",marginBottom:8,background:color||"#c0392b"}}>{title}</div>}<div style={{fontSize:".85rem",lineHeight:1.5}}>{lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>);

const DocMenu=({restaurant,items,footer})=>(<div style={{background:"#1c0a00",color:"#f0e6d3",borderRadius:10,padding:"1.2rem",maxWidth:320,marginBottom:"1rem",border:"1px solid #3a2515"}}><div style={{fontWeight:700,fontSize:".9rem",textAlign:"center",marginBottom:8,paddingBottom:8,borderBottom:"1px solid #3a2515"}}>{restaurant}</div>{items.map((it,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",fontSize:".82rem",marginBottom:3}}><span>{it.name}</span>{it.price&&<span style={{color:"#d4a574",fontFamily:"monospace",fontWeight:700}}>{it.price}</span>}</div>)}{footer&&<div style={{marginTop:8,paddingTop:8,borderTop:"1px solid #3a2515",fontSize:".75rem",textAlign:"center",color:"#a0886e"}}>{footer}</div>}</div>);

const DocBillet=({lines})=>(<div style={{background:"#f5f0e8",color:"#333",borderRadius:8,maxWidth:380,marginBottom:"1rem",overflow:"hidden",border:"1px dashed #ccc"}}><div style={{background:"#1a3a5c",color:"#fff",padding:".5rem .8rem",fontFamily:"monospace",fontSize:".75rem",fontWeight:700}}>BILLET</div><div style={{padding:".8rem",fontSize:".82rem",lineHeight:1.6}}>{lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>);

const DocLettre=({header,body,signature})=>(<div style={{background:"#fefdf8",color:"#333",borderRadius:6,padding:"1.2rem",maxWidth:500,marginBottom:"1rem",border:"1px solid #ddd",fontSize:".85rem",lineHeight:1.6}}>{header&&<div style={{fontWeight:700,fontSize:".82rem",color:"#555",marginBottom:8,paddingBottom:8,borderBottom:"1px solid #eee"}}>{header}</div>}<div style={{whiteSpace:"pre-line"}}>{body}</div>{signature&&<div style={{marginTop:"1rem",paddingTop:8,borderTop:"1px solid #eee",fontStyle:"italic",color:"#666",fontSize:".8rem",whiteSpace:"pre-line"}}>{signature}</div>}</div>);

const DocAffiche=({title,lines,color})=>(<div style={{background:"#0d1425",borderRadius:10,padding:"1.2rem",maxWidth:380,marginBottom:"1rem",border:`2px solid ${color||"#2980b9"}`,textAlign:"center"}}><div style={{fontWeight:800,fontSize:"1rem",marginBottom:8,color:color||"#2980b9"}}>{title}</div><div style={{fontSize:".85rem",lineHeight:1.5,color:"#e2e8f0"}}>{lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>);

const DocEmail=({from,to,subject,body})=>(<div style={{background:"#f8f9fa",color:"#333",borderRadius:8,padding:"1rem",maxWidth:480,marginBottom:"1rem",border:"1px solid #ddd",fontSize:".82rem",lineHeight:1.5}}><div style={{padding:"2px 0",borderBottom:"1px solid #eee"}}><b style={{color:"#666",fontSize:".75rem"}}>De :</b> {from}</div><div style={{padding:"2px 0",borderBottom:"1px solid #eee"}}><b style={{color:"#666",fontSize:".75rem"}}>{"\u00c0"} :</b> {to}</div><div style={{padding:"2px 0",borderBottom:"1px solid #eee"}}><b style={{color:"#666",fontSize:".75rem"}}>Objet :</b> <strong>{subject}</strong></div><div style={{marginTop:8,whiteSpace:"pre-line"}}>{body}</div></div>);

const DocArticle=({source,title,body})=>(<div style={{background:"#0d1425",borderRadius:8,padding:"1.2rem",maxWidth:600,marginBottom:"1rem",border:"1px solid rgba(0,212,255,.1)"}}>{source&&<div style={{fontFamily:"monospace",fontSize:".65rem",color:"#00d4ff",textTransform:"uppercase",letterSpacing:".05em",marginBottom:8}}>{source}</div>}{title&&<div style={{fontWeight:700,fontSize:".95rem",marginBottom:8,color:"#fff"}}>{title}</div>}<div style={{fontSize:".85rem",lineHeight:1.65,color:"#94a3b8"}}>{body}</div></div>);

const DocNote=({body})=>(<div style={{background:"#fff9c4",color:"#333",borderRadius:6,padding:"1rem",maxWidth:320,marginBottom:"1rem",boxShadow:"2px 2px 8px rgba(0,0,0,.15)",transform:"rotate(-1deg)",position:"relative"}}><div style={{position:"absolute",top:-8,left:"50%",transform:"translateX(-50%)",fontSize:"1.2rem"}}>{"\ud83d\udccc"}</div><div style={{fontSize:".85rem",lineHeight:1.5,whiteSpace:"pre-line",paddingTop:4}}>{body}</div></div>);

const Doc=({d})=>{if(!d)return null;const M={sms:DocSMS,panneau:DocPanneau,menu:DocMenu,billet:DocBillet,lettre:DocLettre,affiche:DocAffiche,email:DocEmail,article:DocArticle,note:DocNote};const C=M[d.type];return C?<C {...d}/>:<DocArticle body={d.body}/>};


const Q=[

    {id:1, doc:{type:"menu",restaurant:"🥐 Boulangerie Saint-Denis",items:[{name:"Croissant",price:"2,25 $"},{name:"Pain au chocolat",price:"2,75 $"},{name:"Café allongé",price:"2,50 $"},{name:"COMBO : viennoiserie AU CHOIX + café",price:"3,95 $"}]}, q:"Combien économise-t-on avec le combo si on prend un pain au chocolat et un café ?", o:["0,30 $.","1,30 $.","0,75 $.","Aucune économie."], c:1},
    {id:2, doc:{type:"panneau",title:"ZONE SCOLAIRE",lines:["Limite : 30 km/h","Lundi au vendredi : 7h – 9h et 14h30 – 16h30","Hors de ces heures : 50 km/h"],icon:"🏫",color:"#f39c12"}, q:"À quelle vitesse peut-on rouler un mardi à 12h ?", o:["30 km/h.","50 km/h.","40 km/h.","La zone est interdite à la circulation."], c:1},
    {id:3, doc:{type:"email",from:"Bibliothèque de Laval",to:"p.gagnon@mail.ca",subject:"Rappel — Documents en retard",body:"Bonjour,\nLes documents suivants devaient être rendus le 5 mars :\n- « Le Petit Prince » (livre)\n- « Incendies » (DVD)\nDes frais de retard de 0,25 $/jour/document s'appliquent depuis le 6 mars. Merci de les retourner dès que possible."}, q:"Depuis quand les frais de retard s'appliquent-ils ?", o:["Depuis le 5 mars.","Depuis le 6 mars.","Depuis la réception de ce courriel.","Aucun frais n'est appliqué."], c:1},
    {id:4, doc:{type:"sms",from:"Lina",time:"11:45",message:"Le pédiatre peut nous recevoir à 15h30 mais il faut confirmer avant 13h sinon il donne le créneau à quelqu'un d'autre. Tu peux m'appeler ?"}, q:"Que se passera-t-il si Lina ne confirme pas avant 13h ?", o:["Le rendez-vous sera reporté au lendemain.","Le créneau sera donné à un autre patient.","Le pédiatre appellera directement.","Rien, le rendez-vous est déjà confirmé."], c:1},
    {id:5, doc:{type:"panneau",title:"CAMPING LAC-ÉCHO",lines:["Tarifs : Tente 25 $/nuit — Roulotte 35 $/nuit","Électricité : 5 $ supplément","Bois de chauffage : vendu à l'accueil","Chiens en laisse en tout temps"],color:"#4caf50"}, q:"Combien coûte une nuit en roulotte avec électricité ?", o:["35 $.","40 $.","30 $.","25 $."], c:1},
    {id:6, doc:{type:"affiche",title:"COLLECTE DE SANG",lines:["Héma-Québec","Mardi 25 mars — 13h à 19h","Centre communautaire Saint-Roch","Apportez une pièce d'identité avec photo","⚠️ Avoir mangé dans les 4 heures précédentes"],color:"#e74c3c"}, q:"Que doit avoir fait le donneur avant de se présenter ?", o:["Avoir jeûné pendant 4 heures.","Avoir mangé dans les 4 heures précédentes.","Avoir bu au moins 2 litres d'eau.","Avoir fait un test sanguin récent."], c:1},
    {id:7, doc:{type:"note",body:"Chers locataires,\nLe chauffage sera coupé le vendredi 21 mars de 8h à 14h pour réparation de la chaudière. La température intérieure pourrait descendre à 16°C. Prévoyez des couvertures supplémentaires.\n— Gestion de l'immeuble"}, q:"Pourquoi le chauffage sera-t-il coupé ?", o:["Pour réduire la consommation d'énergie.","Pour réparer la chaudière.","Pour installer un nouveau système de chauffage.","Pour tester les alarmes incendie."], c:1},
    {id:8, doc:{type:"panneau",lines:["🅿️ STATIONNEMENT INCITATIF","Réservé aux usagers du transport en commun","Gratuit avec preuve d'abonnement STM","Sans abonnement : 12 $/jour"],color:"#1565c0"}, q:"Ce stationnement est-il gratuit pour tous ?", o:["Oui, toujours.","Non, seulement pour les abonnés au transport en commun.","Oui, les 2 premières heures.","Non, il coûte 12 $ pour tous."], c:1},
    {id:9, doc:{type:"carte_postale",dest:"Grand-Papa André\n88 rue du Moulin\nRimouski (QC)",body:"Cher Grand-Papa,\nOn s'amuse bien à Tremblant ! La montagne est magnifique mais il n'y a presque pas de neige cette année, alors on fait surtout de la randonnée. On rentre mardi.",signature:"Gros bisous, Camille"}, q:"Pourquoi Camille ne fait-elle pas de ski ?", o:["Parce qu'elle n'aime pas le ski.","Parce qu'il n'y a presque pas de neige.","Parce que les pistes sont fermées pour travaux.","Parce que c'est trop cher."], c:1},
    {id:10, doc:{type:"panneau",title:"CLINIQUE SANS RENDEZ-VOUS",lines:["Ouverte 7 jours sur 7","Lun–Ven : 8h – 20h","Sam–Dim : 9h – 17h","⚠️ Dernier patient accepté 1h avant la fermeture"],color:"#27ae60"}, q:"Peut-on se présenter le samedi à 16h30 ?", o:["Oui, la clinique ferme à 17h.","Non, le dernier patient est accepté à 16h.","Oui, sans aucune restriction.","Non, la clinique est fermée le samedi."], c:1},
    // B1/B2
    {id:11, doc:{type:"article",source:"Le Devoir — Consommation",body:"Le gouvernement fédéral a interdit les plastiques à usage unique en 2023. Deux ans plus tard, un rapport révèle que la production de plastique au Canada a en fait augmenté de 3 %, car l'interdiction ne couvre que six catégories d'objets (pailles, sacs, couverts, etc.) et ne s'applique pas aux emballages industriels, qui représentent 70 % du plastique produit."}, q:"Pourquoi l'interdiction n'a-t-elle pas réduit la production de plastique ?", o:["Les Canadiens contournent la loi en important du plastique.","L'interdiction ne couvre qu'une fraction du plastique produit, excluant l'emballage industriel.","Les entreprises refusent de se conformer à la loi.","Le plastique à usage unique a été remplacé par un matériau plus polluant."], c:1},
    {id:12, doc:{type:"article",source:"Radio-Canada — Transport",body:"Le REM de Montréal a ouvert sa première ligne avec un mois de retard et des problèmes techniques récurrents : portes bloquées, pannes électriques, signalisation défaillante. Le consortium privé responsable minimise ces « ajustements normaux ». Les usagers, eux, comparent l'expérience au métro existant, vieux de 50 ans mais jugé plus fiable."}, q:"Comment les usagers perçoivent-ils le REM par rapport à l'ancien métro ?", o:["Plus moderne et plus fiable.","Moins fiable malgré sa modernité.","Identique en termes de fiabilité.","Meilleur mais plus cher."], c:1},
    {id:13, doc:{type:"article",source:"Le Soleil — Agriculture",body:"Les fermes verticales, ces installations urbaines où les légumes poussent en intérieur sous lumière artificielle, se multiplient au Québec. Elles consomment 95 % moins d'eau que l'agriculture traditionnelle. Cependant, leur consommation d'électricité est considérable et leur rentabilité reste fragile : une laitue de ferme verticale coûte 3 $ à produire contre 0,80 $ en champ."}, q:"Quel est le principal inconvénient des fermes verticales ?", o:["Elles consomment trop d'eau.","Leur coût de production est bien plus élevé que l'agriculture traditionnelle.","Les légumes produits sont de moindre qualité.","Elles ne peuvent cultiver que de la laitue."], c:1},
    {id:14, doc:{type:"article",source:"La Presse — Société",body:"Le tribunal administratif du Québec a rendu une décision controversée : un propriétaire peut refuser un animal de soutien émotionnel dans son logement, contrairement aux animaux d'assistance certifiés (chien-guide, etc.). Les défenseurs de la santé mentale dénoncent une distinction discriminatoire ; les propriétaires invoquent le droit de propriété et les risques de dommages."}, q:"Quelle distinction le tribunal établit-il ?", o:["Entre animaux de compagnie et animaux sauvages.","Entre animaux d'assistance certifiés (protégés) et animaux de soutien émotionnel (non protégés).","Entre grands et petits animaux.","Entre locataires et propriétaires d'animaux."], c:1},
    {id:15, doc:{type:"article",source:"Le Journal de Montréal — Économie",body:"L'industrie du jeu vidéo à Montréal emploie 15 000 personnes et génère 1,5 milliard $ de revenus annuels, en grande partie grâce à des crédits d'impôt généreux de 37,5 %. Les critiques estiment que cet argent public bénéficie surtout aux multinationales (Ubisoft, EA) plutôt qu'aux studios indépendants locaux, qui ne représentent que 8 % des emplois du secteur."}, q:"Quelle critique est formulée à l'égard des crédits d'impôt au jeu vidéo ?", o:["Ils coûtent trop cher au gouvernement.","Ils profitent principalement aux multinationales plutôt qu'aux studios locaux.","Ils n'ont créé aucun emploi.","Ils favorisent l'immigration de travailleurs étrangers."], c:1},
    {id:16, doc:{type:"article",source:"Le Devoir — Éducation",body:"Le Cégep de Rimouski a ouvert un programme de formation en intelligence artificielle appliquée. Les 30 places ont été comblées en 48 heures. Les étudiants sont attirés par un salaire d'entrée moyen de 65 000 $ et un taux de placement de 100 %. Le directeur tempère : « la technologie évolue si vite que la moitié de ce qu'on enseigne sera obsolète dans trois ans »."}, q:"Quelle nuance le directeur apporte-t-il ?", o:["Que le programme est trop cher.","Que le contenu deviendra rapidement obsolète vu la vitesse d'évolution technologique.","Que les étudiants ne sont pas assez motivés.","Que le salaire d'entrée est exagéré."], c:1},
    {id:17, doc:{type:"article",source:"La Presse — Environnement",body:"La Ville de Montréal a planté 500 000 arbres en cinq ans dans le cadre de son plan canopée. Mais une étude de l'UQAM révèle que 35 % des arbres plantés sont morts dans les deux premières années, principalement faute d'arrosage adéquat et à cause de sols trop compactés. Le bilan réel serait donc de 325 000 arbres survivants."}, q:"Pourquoi le bilan de la plantation d'arbres est-il décevant ?", o:["Les espèces choisies n'étaient pas adaptées au climat.","35 % des arbres sont morts par manque d'arrosage et sols compactés.","Les citoyens ont arraché les arbres plantés.","Le budget était insuffisant pour planter autant d'arbres."], c:1},
    {id:18, doc:{type:"article",source:"Le Devoir — Logement",body:"Le Québec a plafonné les augmentations de loyer à l'indice du coût de la vie (estimé à 3,1 % en 2026). Les propriétaires qui souhaitent rénover peuvent demander une hausse supérieure au Tribunal administratif du logement. Les associations de locataires dénoncent cette exception, affirmant que certains propriétaires font des « rénovictions » — des rénovations cosmétiques dont le but réel est d'évincer les locataires pour relouer plus cher."}, q:"Que sont les « rénovictions » ?", o:["Des rénovations écologiques subventionnées.","Des rénovations utilisées comme prétexte pour évincer les locataires et augmenter les loyers.","Des évictions ordonnées par le tribunal pour cause d'insalubrité.","Des rénovations imposées par la ville."], c:1},
    {id:19, doc:{type:"article",source:"Radio-Canada — Culture",body:"Le gouvernement du Québec exige que les films diffusés sur les plateformes de streaming (Netflix, Disney+) incluent 30 % de contenu francophone. Netflix a répondu en ajoutant des films français de France, ce qui ne satisfait pas les cinéastes québécois, qui réclament un quota spécifique de contenu QUÉBÉCOIS, et non simplement francophone."}, q:"Pourquoi les cinéastes québécois ne sont-ils pas satisfaits ?", o:["Netflix refuse d'offrir du contenu en français.","Le quota francophone est rempli avec du contenu français, pas québécois.","Les films québécois sont retirés des plateformes.","Netflix a augmenté ses prix au Québec."], c:1},
    {id:20, doc:{type:"article",source:"Le Soleil — Santé publique",body:"Le Québec a été la première province à interdire les saveurs dans le tabac et le vapotage. Le tabagisme chez les 15-19 ans a chuté de 40 % en dix ans. Paradoxe : l'usage de sachets de nicotine (non réglementés car classés comme « produits de consommation ») a explosé chez le même groupe d'âge, les adolescents les trouvant « discrets » et « sans odeur »."}, q:"Quel phénomène illustre les limites de la réglementation antitabac ?", o:["Le tabagisme a augmenté malgré la loi.","Les adolescents se sont tournés vers les sachets de nicotine, non réglementés.","Les jeunes achètent du tabac en contrebande.","Les saveurs n'avaient aucun effet sur les jeunes."], c:1},
    {id:21, doc:{type:"article",source:"Le Devoir — Autochtones",body:"Le gouvernement fédéral a versé 4,3 milliards $ en indemnisations aux enfants autochtones retirés de force de leur famille par les services sociaux. Le règlement a été salué, mais un rapport de suivi montre que le nombre d'enfants autochtones en famille d'accueil n'a pas diminué depuis. Les indemnisations financières n'ont pas changé les pratiques institutionnelles qui causent le problème."}, q:"Pourquoi le règlement financier est-il jugé insuffisant ?", o:["Le montant est trop faible.","Il n'a pas modifié les pratiques qui causent les retraits d'enfants.","Les familles ont refusé l'argent.","Le gouvernement n'a pas respecté ses engagements financiers."], c:1},
    {id:22, doc:{type:"article",source:"Québec Science",body:"Les microplastiques se retrouvent désormais dans la neige de l'Arctique canadien, à des concentrations comparables à celles des grandes villes européennes. L'atmosphère transporte ces particules sur des milliers de kilomètres. Les chercheurs soulignent qu'aucun écosystème sur Terre n'est plus épargné — même les zones qu'on croyait « vierges » sont contaminées."}, q:"Que révèle cette découverte sur les microplastiques ?", o:["L'Arctique est plus pollué que les villes.","Aucun écosystème sur Terre n'est épargné par la contamination.","Les microplastiques sont naturellement présents dans la neige.","Le transport atmosphérique de polluants est un phénomène récent."], c:1},
    {id:23, doc:{type:"article",source:"La Presse — Technologie",body:"Le gouvernement québécois a lancé un « identifiant numérique » pour remplacer le permis de conduire et la carte d'assurance maladie. Les 50 000 premiers utilisateurs signalent des problèmes : fichiers corrompus, temps de chargement excessifs et incompatibilité avec 40 % des lecteurs utilisés par les commerçants."}, q:"Pourquoi l'identifiant numérique pose-t-il problème ?", o:["Les citoyens refusent d'abandonner leurs cartes physiques.","Des problèmes techniques (fichiers, temps de chargement, incompatibilité) persistent.","Le gouvernement a abandonné le projet.","Les commerçants s'y opposent pour des raisons idéologiques."], c:1},
    {id:24, doc:{type:"article",source:"Le Devoir — Logement",body:"Montréal compte 25 000 logements vacants selon Statistique Canada, alors que 80 000 ménages sont sur une liste d'attente pour un logement social. La ville a adopté une taxe sur les logements vacants de 1 % de la valeur. Les critiques jugent ce taux insuffisant : « À 1 %, il est plus rentable de garder un logement vide que de le louer à prix modéré. »"}, q:"Pourquoi la taxe sur les logements vacants est-elle jugée inefficace ?", o:["Parce qu'il n'y a pas assez de logements vacants.","Parce que son taux est trop bas pour dissuader les propriétaires.","Parce que les propriétaires ne la paient pas.","Parce qu'elle s'applique uniquement aux nouvelles constructions."], c:1},
    // C1/C2
    {id:25, doc:{type:"article",source:"Essai — Fédéralisme",body:"Le fédéralisme canadien oscille entre deux tentations symétriques : une centralisation qui garantit l'uniformité au prix de la diversité, et une décentralisation qui respecte les particularismes au risque de l'incohérence. La sagesse politique ne consiste pas à choisir un pôle mais à naviguer dans la tension — à accepter qu'un pays de cette étendue et de cette complexité ne sera jamais entièrement uniforme ni entièrement cohérent."}, q:"Que recommande l'auteur ?", o:["Une centralisation complète pour plus d'efficacité.","D'accepter la tension entre unité et diversité plutôt que de la résoudre.","Une décentralisation maximale pour respecter les provinces.","La dissolution de la fédération."], c:1},
    {id:26, doc:{type:"text",body:"Ce n'est pas le froid qui surprend quand on arrive à Montréal en janvier — c'est le silence qu'il impose. Les pas crissent sur la neige avec une discrétion qui semble respecter quelque chose, une intimité entre la ville et l'hiver que l'étranger ne peut que deviner. Et puis il y a cette lumière, rasante, dorée, qui transforme les façades les plus banales en tableaux — comme si le froid, en dépouillant le monde de ses distractions, révélait ce qu'on ne voyait plus."}, q:"Quel effet le froid a-t-il selon le narrateur ?", o:["Il rend la ville hostile et inhospitalière.","Il révèle une beauté habituellement invisible en éliminant les distractions.","Il décourage les touristes de visiter Montréal.","Il crée une atmosphère triste et oppressante."], c:1},
    {id:27, doc:{type:"article",source:"Essai — Revenu universel",body:"Le revenu universel suscite un paradoxe : les libéraux y voient un outil de simplification de l'État-providence (donc de réduction de l'État), tandis que les progressistes y voient un filet émancipateur (donc un renforcement de la solidarité). Que deux idéologies opposées convergent vers le même dispositif devrait susciter non l'enthousiasme mais la prudence : si tout le monde est d'accord, c'est peut-être que personne ne parle de la même chose."}, q:"Pourquoi la convergence idéologique doit-elle susciter la prudence ?", o:["Parce que le revenu universel coûte trop cher.","Parce que des visions opposées convergent peut-être vers des interprétations incompatibles.","Parce que les deux camps politiques sont de mauvaise foi.","Parce que l'unanimité est toujours suspecte en démocratie."], c:1},
    {id:28, doc:{type:"article",source:"Sociologie — Résilience",body:"Le discours de la « résilience » ne célèbre pas une vertu — il normalise une violence. En enjoignant aux individus de « rebondir » face à des conditions structurellement dégradées, on opère un glissement : ce qui était un problème collectif (chômage, précarité, crise climatique) devient un défi individuel. La résilience, dans cette acception, est l'opium des politiques impuissantes."}, q:"Quel reproche l'auteur adresse-t-il au discours de la résilience ?", o:["Il est scientifiquement infondé.","Il individualise des problèmes collectifs et décharge les institutions de leur responsabilité.","Il décourage les gens de faire face aux difficultés.","Il est utilisé exclusivement dans le domaine de la santé mentale."], c:1},
    {id:29, doc:{type:"article",source:"Philosophie morale — Pardon",body:"Le pardon, dans la tradition chrétienne, est un acte de générosité unilatérale. Mais cette conception pose un problème que la philosophe Hannah Arendt a identifié : en pardonnant sans condition, on prive la victime de son droit à la colère — on lui demande de renoncer à la seule émotion qui reconnaisse pleinement le tort qui lui a été fait. Le pardon n'est pas toujours libérateur ; parfois, il est une seconde violence."}, q:"Selon Arendt (telle que présentée ici), pourquoi le pardon peut-il être problématique ?", o:["Parce qu'il encourage le coupable à recommencer.","Parce qu'il prive la victime de son droit à la colère et à la reconnaissance du tort.","Parce qu'il est contraire aux principes du droit.","Parce qu'il impose une réconciliation forcée entre les parties."], c:1},
    {id:30, doc:{type:"article",source:"Épistémologie — Consensus",body:"La force du consensus scientifique ne réside pas dans l'unanimité mais dans la méthode. Un million de personnes qui croient quelque chose sans preuve ne constituent pas un consensus scientifique. Dix chercheurs dont les résultats, obtenus indépendamment, convergent vers la même conclusion, si. La science ne compte pas les voix — elle pèse les preuves."}, q:"Quelle différence l'auteur établit-il entre consensus scientifique et opinion majoritaire ?", o:["Le consensus repose sur le nombre de chercheurs qui sont d'accord.","Le consensus repose sur la convergence de preuves indépendantes, pas sur le nombre de voix.","L'opinion majoritaire est plus fiable que le consensus scientifique.","Il n'y a aucune différence entre les deux."], c:1},
    {id:31, doc:{type:"article",source:"Essai — Éducation",body:"L'inflation des diplômes — le fait qu'un poste autrefois accessible avec un DEC exige désormais un bac, et qu'un bac ne suffit plus là où une maîtrise est maintenant requise — ne profite à personne. Ni aux employeurs, qui n'obtiennent pas de candidats plus compétents, ni aux étudiants, qui s'endettent davantage pour un titre dont la valeur s'érode. Le seul gagnant est l'institution universitaire elle-même, qui remplit ses amphithéâtres."}, q:"Qui profite de l'inflation des diplômes selon l'auteur ?", o:["Les employeurs, qui obtiennent des candidats plus qualifiés.","L'institution universitaire, qui remplit ses classes.","Les étudiants, qui accèdent à de meilleurs emplois.","Personne ne profite de ce phénomène."], c:1},
    {id:32, doc:{type:"article",source:"Essai — Attention",body:"Le vrai coût de l'économie de l'attention n'est pas le temps perdu mais la capacité de penser perdue. Une notification n'interrompt pas seulement une tâche — elle fragmente la pensée en morceaux trop petits pour qu'une idée complexe puisse s'y former. L'appauvrissement cognitif ne se mesure pas en heures de scrolling mais en pensées qui n'ont jamais eu le temps de naître."}, q:"Quel est le « vrai coût » de l'économie de l'attention selon l'auteur ?", o:["Le temps passé sur les écrans.","La perte de la capacité à former des pensées complexes.","La dépendance aux réseaux sociaux.","La diminution de la productivité au travail."], c:1},
    {id:33, doc:{type:"article",source:"Sémiotique — Publicité",body:"L'image publicitaire ne vend pas un produit — elle vend un manque. Son efficacité ne repose pas sur l'information qu'elle transmet mais sur le désir qu'elle crée. La femme souriante sur l'affiche du parfum ne dit pas « ce parfum sent bon » ; elle dit « sans ce parfum, il vous manque quelque chose ». La publicité est, fondamentalement, un art de l'insuffisance créée."}, q:"Que vend réellement la publicité selon l'auteur ?", o:["Un produit et ses qualités objectives.","Un sentiment de manque et d'insuffisance.","Un rêve de bonheur accessible à tous.","Une information fiable sur les produits."], c:1},
    {id:34, doc:{type:"article",source:"Anthropocène — Essai",body:"La distinction nature/culture, fondatrice de la modernité, est un obstacle épistémologique. En s'excluant conceptuellement de la nature, l'humanité s'est autorisée à la traiter comme un simple réservoir de ressources. Le mot « environnement » trahit cette conception : il suppose un centre (l'humain) et une périphérie (tout le reste). Penser écologiquement, c'est abolir cette géographie mentale."}, q:"Que critique l'auteur dans le mot « environnement » ?", o:["Son imprécision scientifique.","Le fait qu'il place l'humain au centre et la nature en périphérie.","Son utilisation excessive dans les médias.","Le fait qu'il soit difficile à traduire dans d'autres langues."], c:1},
    {id:35, doc:{type:"text",body:"Le problème avec les souvenirs, pensa Léonard, c'est qu'ils ne restent jamais fidèles. Chaque convocation les modifie — un détail s'efface, un autre s'invente. Sa mère, par exemple : était-elle vraiment aussi douce ? Ou avait-il, au fil des années, sculpté une tendresse qui n'avait peut-être jamais existé ? Le souvenir le plus douloureux n'était pas la perte — c'était cette incertitude : ne plus savoir si ce qu'on regrette a vraiment eu lieu."}, q:"Quelle est la souffrance la plus profonde de Léonard ?", o:["La mort de sa mère.","L'incertitude de ne plus savoir si ses souvenirs sont vrais.","Le passage du temps qui efface tout.","L'impossibilité de communiquer avec les morts."], c:1},
    {id:36, doc:{type:"article",source:"Justice réparatrice",body:"La justice réparatrice ne cherche pas à punir mais à restaurer. Son paradoxe est que cette restauration exige parfois plus de courage qu'une condamnation : le face-à-face entre l'auteur du délit et sa victime est une épreuve que le système pénal, en interposant des avocats et des procédures, permet justement d'éviter. La justice réparatrice enlève les médiations et confronte chacun à la nudité des faits."}, q:"Pourquoi la justice réparatrice peut-elle exiger plus de courage que le système pénal traditionnel ?", o:["Parce que les peines sont plus sévères.","Parce qu'elle confronte directement l'auteur et la victime sans médiation procédurale.","Parce qu'elle est plus lente.","Parce que les victimes doivent pardonner obligatoirement."], c:1},
    {id:37, doc:{type:"article",source:"Capitalisme de surveillance — Zuboff",body:"Le capitalisme de surveillance ne se contente pas de prédire notre comportement — il cherche à le modifier. Les notifications, les nudges, les interfaces addictives ne sont pas des accidents de design ; ce sont des instruments d'un « behaviorisme du marché » dont l'objectif est de rendre le comportement humain aussi prévisible — et donc aussi monnayable — que possible."}, q:"Quel est l'objectif ultime du capitalisme de surveillance selon Zuboff ?", o:["Vendre des publicités ciblées.","Rendre le comportement humain prévisible et monnayable.","Collecter des données pour améliorer les services.","Contrôler politiquement la population."], c:1},
    {id:38, doc:{type:"article",source:"Esthétique — Sublime",body:"Le sublime naît d'un excès qui dépasse notre capacité de représentation. Face à l'immensité de l'océan, nous éprouvons simultanément notre insignifiance physique et l'élévation de notre pensée, capable de concevoir ce que nos sens ne peuvent saisir. Le beau rassure ; le sublime inquiète — et c'est dans cette inquiétude que réside sa puissance."}, q:"Quelle différence fondamentale sépare le beau du sublime ?", o:["Le beau est naturel, le sublime est artificiel.","Le beau rassure tandis que le sublime inquiète par un excès qui nous dépasse.","Le sublime est une forme supérieure du beau.","Le beau est objectif tandis que le sublime est subjectif."], c:1},
    {id:39, doc:{type:"article",source:"Essai final",body:"La question ultime de l'Anthropocène n'est pas « que faire ? » — nous le savons — mais « pourquoi ne le faisons-nous pas ? ». La réponse se trouve peut-être dans la structure même de notre pensée : nous sommes câblés pour répondre aux menaces immédiates et visibles, pas aux processus lents et invisibles. Le changement climatique est un prédateur que notre cerveau de chasseur-cueilleur n'est pas équipé pour percevoir."}, q:"Selon l'auteur, pourquoi l'humanité ne réagit-elle pas à la crise climatique ?", o:["Parce que les solutions n'existent pas encore.","Parce que notre cerveau est mal adapté pour percevoir des menaces lentes et invisibles.","Parce que les gouvernements cachent la vérité.","Parce que les conséquences ne se feront sentir que dans un futur lointain."], c:1},
];

function sc(a){let x=0,y=0,z=0;Q.forEach((q,i)=>{const ok=a[i]===q.c;if(i<10&&ok)x++;else if(i<24&&ok)y++;else if(i>=24&&ok)z++});const xp=x/10,yp=y/14,zp=z/15,t=x+y+z,tp=t/39;let n;if(zp>=.8&&yp>=.7)n=tp>=.85?10:tp>=.75?9:8;else if(zp>=.5&&yp>=.6)n=tp>=.65?7:6;else if(yp>=.5&&xp>=.7)n=tp>=.55?6:5;else if(xp>=.7&&yp>=.3)n=4;else if(xp>=.5)n=3;else n=2;const lv=n>=9?"C2":n>=7?"C1":n>=6?"B2":n>=4?"B1":n>=3?"A2":"A1";return{nclc:n,level:lv,total:t,a1a2:x,b1b2:y,c1c2:z,xp,yp,zp}}

const C={bg:"#080c16",s1:"#0d1425",cy:"#00d4ff",ind:"#6366f1",gn:"#10b981",bl:"#3b82f6",rd:"#ef4444",am:"#f59e0b",tx:"#e2e8f0",txm:"#94a3b8",txd:"#64748b"};
const base={fontFamily:"system-ui,sans-serif",background:C.bg,color:C.tx,minHeight:"100vh"};
const b1={fontWeight:700,fontSize:".85rem",letterSpacing:".08em",textTransform:"uppercase",background:`linear-gradient(135deg,${C.cy},${C.ind})`,color:"#fff",border:"none",padding:".9rem 2.5rem",borderRadius:8,cursor:"pointer"};
const b2={fontSize:".8rem",background:"transparent",color:C.txm,border:"1px solid rgba(0,212,255,.15)",padding:".6rem 1.2rem",borderRadius:6,cursor:"pointer",fontFamily:"inherit"};
const b3={...b1,fontSize:".75rem",padding:".6rem 1.2rem",background:`linear-gradient(135deg,${C.gn},#059669)`};

export default function App(){
  const nav=useNavigate();
  const[pg,setPg]=useState("home");
  const[ci,setCi]=useState(0);
  const[ans,setAns]=useState({});
  const[sec,setSec]=useState(3600);
  const[on,setOn]=useState(false);
  const[pop,setPop]=useState(false);
  const[fl,setFl]=useState(new Set());
  const[nv,setNv]=useState(false);
  const[res,setRes]=useState(null);
  const tr=useRef(null);

  useEffect(()=>{if(!on)return;tr.current=setInterval(()=>setSec(p=>{if(p<=1){clearInterval(tr.current);return 0}return p-1}),1000);return()=>clearInterval(tr.current)},[on]);
  useEffect(()=>{if(sec===0&&on){setOn(false);setRes(sc(ans));setPg("results")}},[sec,on,ans]);

  const go=()=>{setAns({});setCi(0);setSec(3600);setOn(true);setFl(new Set());setNv(false);setPg("quiz")};
  const fin=()=>{setOn(false);clearInterval(tr.current);setRes(sc(ans));setPg("results")};
  const pk=(i,j)=>setAns(p=>({...p,[i]:j}));
  const fg=i=>{setFl(p=>{const n=new Set(p);n.has(i)?n.delete(i):n.add(i);return n})};
  const fm=s=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;
  const ct=Object.keys(ans).length;
  const L=["A","B","C","D"];

  if(pg==="home")return(
    <div style={base}><div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",minHeight:"100vh",padding:"2rem",textAlign:"center"}}>
      <div style={{fontSize:".65rem",color:C.cy,letterSpacing:".15em",textTransform:"uppercase",marginBottom:"2rem",fontFamily:"monospace"}}>FLAB GAMES</div>
      <h1 style={{fontSize:"clamp(2rem,7vw,3.5rem)",fontWeight:900,background:`linear-gradient(135deg,#fff,${C.cy},${C.ind})`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",lineHeight:1,marginBottom:8}}>ESCAPE LAB</h1>
      <p style={{fontSize:"clamp(.75rem,2vw,1rem)",color:C.txm,letterSpacing:".15em",textTransform:"uppercase",marginBottom:"1.5rem"}}>S{"\u00e9"}rie Delta {"\u2014"} TCF Canada</p>
      <p style={{fontSize:".9rem",color:C.txd,maxWidth:460,lineHeight:1.6,marginBottom:"2.5rem"}}>39 questions avec vrais pi{"\u00e8"}ges. 60 minutes. A1{"\u2192"}C2.</p>
      <button style={b1} onClick={go}>COMMENCER</button>
      <div style={{display:"flex",gap:"2rem",marginTop:"2.5rem",flexWrap:"wrap",justifyContent:"center"}}>
        {[["39","Questions"],["60","Min"],["NCLC","Score"]].map(([v,l])=>(<div key={l} style={{textAlign:"center"}}><div style={{fontWeight:700,fontSize:"1.3rem",color:C.cy}}>{v}</div><div style={{fontSize:".6rem",color:C.txd,textTransform:"uppercase"}}>{l}</div></div>))}
      </div>
    </div></div>
  );

  if(pg==="quiz"){const q=Q[ci],ll=ci<10?"A1/A2":ci<24?"B1/B2":"C1/C2",lc=ci<10?C.gn:ci<24?C.bl:C.ind,tc=sec<=300?C.rd:sec<=900?C.am:C.cy;
  return(<div style={base}>
    <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:".6rem 1rem",background:C.s1,borderBottom:"1px solid rgba(0,212,255,.1)",position:"sticky",top:0,zIndex:50,flexWrap:"wrap",gap:4}}>
      <span style={{fontWeight:700,fontSize:".75rem",color:C.cy}}>ESCAPE LAB</span>
      <div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontWeight:700,fontSize:"1.1rem",color:tc,fontFamily:"monospace"}}>{fm(sec)}</span><span style={{fontSize:".65rem",color:C.txd,fontFamily:"monospace"}}>{ct}/39</span></div>
      <div style={{display:"flex",gap:4}}>
        <button onClick={()=>fg(ci)} style={{...b2,padding:"4px 8px",borderColor:fl.has(ci)?C.ind:"rgba(0,212,255,.15)",color:fl.has(ci)?C.ind:C.txm}}>{"\u2691"}</button>
        <button onClick={()=>setNv(!nv)} style={{...b2,padding:"4px 8px"}}>{"\u2630"}</button>
      </div>
    </div>
    <div style={{height:3,background:"#121a32"}}><div style={{height:"100%",width:`${(ct/39)*100}%`,background:`linear-gradient(90deg,${C.cy},${C.ind})`,transition:"width .3s"}}/></div>
    <div style={{maxWidth:780,margin:"0 auto",padding:"1.5rem 1rem",display:"flex",flexDirection:"column",minHeight:"calc(100vh - 60px)"}}>
      <span style={{display:"inline-block",padding:"3px 10px",borderRadius:100,fontSize:".6rem",fontWeight:700,marginBottom:12,border:`1px solid ${lc}33`,color:lc,background:`${lc}11`,alignSelf:"flex-start"}}>Q{ci+1} {"\u00b7"} {ll}</span>
      <Doc d={q.doc}/>
      <p style={{fontWeight:600,fontSize:".95rem",marginBottom:12,color:"#fff"}}>{q.q}</p>
      <div style={{display:"flex",flexDirection:"column",gap:8,marginBottom:"1.5rem"}}>
        {q.o.map((o,i)=>(<button key={i} onClick={()=>pk(ci,i)} style={{display:"flex",alignItems:"flex-start",gap:10,padding:".8rem 1rem",background:ans[ci]===i?"rgba(0,212,255,.06)":C.s1,border:`1px solid ${ans[ci]===i?C.cy:"rgba(0,212,255,.1)"}`,borderRadius:8,cursor:"pointer",textAlign:"left",fontFamily:"inherit",fontSize:".85rem",color:C.tx,lineHeight:1.45,transition:"all .15s"}}>
          <span style={{flexShrink:0,width:26,height:26,borderRadius:5,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"monospace",fontWeight:700,fontSize:".7rem",background:ans[ci]===i?C.cy:"#121a32",color:ans[ci]===i?C.bg:C.txd}}>{L[i]}</span>
          <span>{o}</span>
        </button>))}
      </div>
      <div style={{display:"flex",justifyContent:"space-between",marginTop:"auto",paddingTop:"1rem",gap:8}}>
        <button style={{...b2,opacity:ci===0?.3:1}} onClick={()=>setCi(Math.max(0,ci-1))} disabled={ci===0}>{"\u2190"} Pr{"\u00e9"}c.</button>
        {ci<38?<button style={b2} onClick={()=>setCi(ci+1)}>Suiv. {"\u2192"}</button>:<button style={b3} onClick={()=>setPop(true)}>TERMINER</button>}
      </div>
    </div>
    {nv&&<div onClick={e=>{if(e.target===e.currentTarget)setNv(false)}} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.6)",zIndex:100,display:"flex",justifyContent:"flex-end"}}>
      <div style={{width:"min(360px,88vw)",background:C.s1,padding:"1.2rem",overflowY:"auto",borderLeft:"1px solid rgba(0,212,255,.1)"}}>
        <div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><span style={{fontWeight:700,fontSize:".8rem",color:C.cy}}>NAVIGATION</span><button style={{...b2,padding:"2px 8px"}} onClick={()=>setNv(false)}>{"\u2715"}</button></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(38px,1fr))",gap:5,marginBottom:12}}>
          {Q.map((_,i)=>(<div key={i} onClick={()=>{setCi(i);setNv(false)}} style={{aspectRatio:"1",borderRadius:5,border:`1px solid ${i===ci?C.cy:ans[i]!=null?C.cy+"40":"rgba(0,212,255,.1)"}`,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"monospace",fontSize:".65rem",fontWeight:700,cursor:"pointer",background:ans[i]!=null?C.cy+"1a":"#121a32",color:ans[i]!=null?C.cy:C.txd,boxShadow:i===ci?`0 0 8px ${C.cy}40`:"none",position:"relative"}}>{i+1}{fl.has(i)&&<span style={{position:"absolute",top:-2,right:1,fontSize:".5rem",color:C.am}}>{"\u2691"}</span>}</div>))}
        </div>
        <button style={{...b3,width:"100%"}} onClick={()=>{setNv(false);setPop(true)}}>TERMINER</button>
      </div>
    </div>}
    {pop&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.7)",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",padding:"1rem"}}>
      <div style={{background:C.s1,border:"1px solid rgba(0,212,255,.1)",borderRadius:14,padding:"1.8rem",maxWidth:400,width:"100%",textAlign:"center"}}>
        <div style={{fontSize:"2rem",marginBottom:8}}>{"\u26a0\ufe0f"}</div>
        <div style={{fontWeight:700,color:C.cy,marginBottom:8}}>Terminer ?</div>
        <div style={{fontSize:".82rem",color:C.txm,marginBottom:"1.2rem"}}>{ct}/39.{39-ct>0&&<> {39-ct} sans r{"\u00e9"}ponse.</>}</div>
        <div style={{display:"flex",gap:8,justifyContent:"center"}}><button style={b2} onClick={()=>setPop(false)}>Continuer</button><button style={b3} onClick={()=>{setPop(false);fin()}}>Confirmer</button></div>
      </div>
    </div>}
  </div>)}

  if(pg==="results"&&res){const nc=["#ef4444","#f97316","#f59e0b","#eab308","#84cc16","#22c55e","#10b981","#06b6d4","#3b82f6","#6366f1"];
  return(<div style={base}><div style={{display:"flex",flexDirection:"column",alignItems:"center",padding:"2.5rem 1.2rem"}}>
    <div style={{fontSize:".65rem",color:C.txd,fontFamily:"monospace",letterSpacing:".1em",marginBottom:6}}>S{"\u00c9"}RIE DELTA</div>
    <div style={{fontSize:"3.5rem",fontWeight:900,background:`linear-gradient(135deg,${C.cy},${C.ind})`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>{res.level}</div>
    <div style={{fontFamily:"monospace",fontSize:".85rem",color:C.txm,marginTop:4,marginBottom:"2rem"}}>NCLC : {res.nclc}/10</div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:8,maxWidth:560,width:"100%",marginBottom:"1.5rem"}}>
      {[["Total",res.total,39,C.cy],["A1/A2",res.a1a2,10,C.gn],["B1/B2",res.b1b2,14,C.bl],["C1/C2",res.c1c2,15,C.ind]].map(([l,v,m,c])=>(<div key={l} style={{background:C.s1,border:"1px solid rgba(0,212,255,.1)",borderRadius:8,padding:"1rem",textAlign:"center"}}><div style={{fontSize:".6rem",color:C.txd,fontFamily:"monospace",marginBottom:4}}>{l}</div><div style={{fontWeight:700,fontSize:"1.4rem",color:c}}>{v}/{m}</div><div style={{fontSize:".65rem",color:C.txd}}>{Math.round(v/m*100)}%</div></div>))}
    </div>
    {[["A1/A2",res.xp,C.gn],["B1/B2",res.yp,C.bl],["C1/C2",res.zp,C.ind]].map(([l,p,c])=>(<div key={l} style={{display:"flex",alignItems:"center",gap:8,marginBottom:8,width:"100%",maxWidth:420}}><span style={{fontFamily:"monospace",fontSize:".7rem",color:C.txd,width:42,textAlign:"right"}}>{l}</span><div style={{flex:1,height:7,background:"#121a32",borderRadius:100,overflow:"hidden"}}><div style={{height:"100%",width:`${p*100}%`,background:c,borderRadius:100}}/></div><span style={{fontFamily:"monospace",fontSize:".7rem",color:C.txm,width:32}}>{Math.round(p*100)}%</span></div>))}
    <div style={{display:"flex",gap:2,margin:"1.5rem 0",maxWidth:420,width:"100%"}}>
      {[1,2,3,4,5,6,7,8,9,10].map(n=>(<div key={n} style={{flex:1,height:28,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700,fontSize:".6rem",borderRadius:3,background:n===res.nclc?nc[n-1]:"#121a32",color:n===res.nclc?"#fff":C.txd,transform:n===res.nclc?"scaleY(1.3)":"none"}}>{n}</div>))}
    </div>
    <div style={{display:"flex",gap:8,marginTop:"1rem"}}><button style={b1} onClick={go}>RECOMMENCER</button><button style={b2} onClick={()=>nav("/")}>TOUTES LES S\u00c9RIES</button></div>
  </div></div>)}
  return null;
}
