import { useNavigate } from "react-router-dom";
import { useState, useEffect, useRef } from "react";

const DocSMS=({from,time,message})=>(<div style={{background:"#1a1a2e",borderRadius:16,padding:"1rem",maxWidth:320,border:"2px solid #2a2a4a",marginBottom:"1rem"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8,paddingBottom:6,borderBottom:"1px solid #2a2a4a"}}><span style={{fontWeight:700,fontSize:".85rem",color:"#fff"}}>{from}</span><span style={{fontSize:".7rem",color:"#888",fontFamily:"monospace"}}>{time}</span></div><div style={{background:"#0066cc",color:"#fff",padding:".6rem .9rem",borderRadius:"14px 14px 4px 14px",fontSize:".85rem",lineHeight:1.45,maxWidth:"90%"}}>{message}</div></div>);

const DocPanneau=({title,lines,icon,color})=>(<div style={{background:"#fff",color:"#222",borderRadius:8,padding:"1rem 1.2rem",maxWidth:350,borderLeft:`5px solid ${color||"#c0392b"}`,marginBottom:"1rem",boxShadow:"0 2px 8px rgba(0,0,0,.2)"}}>{icon&&<div style={{fontSize:"1.5rem",marginBottom:4}}>{icon}</div>}{title&&<div style={{color:"#fff",fontWeight:700,fontSize:".8rem",padding:".3rem .6rem",borderRadius:4,display:"inline-block",marginBottom:8,background:color||"#c0392b"}}>{title}</div>}<div style={{fontSize:".85rem",lineHeight:1.5}}>{lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>);

const DocMenu=({restaurant,items,footer})=>(<div style={{background:"#1c0a00",color:"#f0e6d3",borderRadius:10,padding:"1.2rem",maxWidth:320,marginBottom:"1rem",border:"1px solid #3a2515"}}><div style={{fontWeight:700,fontSize:".9rem",textAlign:"center",marginBottom:8,paddingBottom:8,borderBottom:"1px solid #3a2515"}}>{restaurant}</div>{items.map((it,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",fontSize:".82rem",marginBottom:3}}><span>{it.name}</span>{it.price&&<span style={{color:"#d4a574",fontFamily:"monospace",fontWeight:700}}>{it.price}</span>}</div>)}{footer&&<div style={{marginTop:8,paddingTop:8,borderTop:"1px solid #3a2515",fontSize:".75rem",textAlign:"center",color:"#a0886e"}}>{footer}</div>}</div>);

const DocBillet=({lines})=>(<div style={{background:"#f5f0e8",color:"#333",borderRadius:8,maxWidth:380,marginBottom:"1rem",overflow:"hidden",border:"1px dashed #ccc"}}><div style={{background:"#1a3a5c",color:"#fff",padding:".5rem .8rem",fontFamily:"monospace",fontSize:".75rem",fontWeight:700}}>BILLET</div><div style={{padding:".8rem",fontSize:".82rem",lineHeight:1.6}}>{lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>);

const DocLettre=({header,body,signature})=>(<div style={{background:"#fefdf8",color:"#333",borderRadius:6,padding:"1.2rem",maxWidth:500,marginBottom:"1rem",border:"1px solid #ddd",fontSize:".85rem",lineHeight:1.6}}>{header&&<div style={{fontWeight:700,fontSize:".82rem",color:"#555",marginBottom:8,paddingBottom:8,borderBottom:"1px solid #eee"}}>{header}</div>}<div style={{whiteSpace:"pre-line"}}>{body}</div>{signature&&<div style={{marginTop:"1rem",paddingTop:8,borderTop:"1px solid #eee",fontStyle:"italic",color:"#666",fontSize:".8rem",whiteSpace:"pre-line"}}>{signature}</div>}</div>);

const DocAffiche=({title,lines,color})=>(<div style={{background:"#0d1425",borderRadius:10,padding:"1.2rem",maxWidth:380,marginBottom:"1rem",border:`2px solid ${color||"#2980b9"}`,textAlign:"center"}}><div style={{fontWeight:800,fontSize:"1rem",marginBottom:8,color:color||"#2980b9"}}>{title}</div><div style={{fontSize:".85rem",lineHeight:1.5,color:"#e2e8f0"}}>{lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>);

const DocEmail=({from,to,subject,body})=>(<div style={{background:"#f8f9fa",color:"#333",borderRadius:8,padding:"1rem",maxWidth:480,marginBottom:"1rem",border:"1px solid #ddd",fontSize:".82rem",lineHeight:1.5}}><div style={{padding:"2px 0",borderBottom:"1px solid #eee"}}><b style={{color:"#666",fontSize:".75rem"}}>De :</b> {from}</div><div style={{padding:"2px 0",borderBottom:"1px solid #eee"}}><b style={{color:"#666",fontSize:".75rem"}}>{"\u00c0"} :</b> {to}</div><div style={{padding:"2px 0",borderBottom:"1px solid #eee"}}><b style={{color:"#666",fontSize:".75rem"}}>Objet :</b> <strong>{subject}</strong></div><div style={{marginTop:8,whiteSpace:"pre-line"}}>{body}</div></div>);

const DocArticle=({source,title,body})=>(<div style={{background:"#0d1425",borderRadius:8,padding:"1.2rem",maxWidth:600,marginBottom:"1rem",border:"1px solid rgba(0,212,255,.1)"}}>{source&&<div style={{fontFamily:"monospace",fontSize:".65rem",color:"#00d4ff",textTransform:"uppercase",letterSpacing:".05em",marginBottom:8}}>{source}</div>}{title&&<div style={{fontWeight:700,fontSize:".95rem",marginBottom:8,color:"#fff"}}>{title}</div>}<div style={{fontSize:".85rem",lineHeight:1.65,color:"#94a3b8"}}>{body}</div></div>);

const DocNote=({body})=>(<div style={{background:"#fff9c4",color:"#333",borderRadius:6,padding:"1rem",maxWidth:320,marginBottom:"1rem",boxShadow:"2px 2px 8px rgba(0,0,0,.15)",transform:"rotate(-1deg)",position:"relative"}}><div style={{position:"absolute",top:-8,left:"50%",transform:"translateX(-50%)",fontSize:"1.2rem"}}>{"\ud83d\udccc"}</div><div style={{fontSize:".85rem",lineHeight:1.5,whiteSpace:"pre-line",paddingTop:4}}>{body}</div></div>);

const Doc=({d})=>{if(!d)return null;const M={sms:DocSMS,panneau:DocPanneau,menu:DocMenu,billet:DocBillet,lettre:DocLettre,affiche:DocAffiche,email:DocEmail,article:DocArticle,note:DocNote};const C=M[d.type];return C?<C {...d}/>:<DocArticle body={d.body}/>};


const Q=[

    {id:1, doc:{type:"panneau",lines:["🏥 URGENCES →","Suivre la ligne bleue au sol","Accueil au bout du couloir à gauche","⚠️ Consultations sans rendez-vous : 1ᵉʳ étage"],color:"#e74c3c"}, q:"Où doit aller une personne qui a besoin des urgences ?",
      o:["Au premier étage.","Suivre la ligne bleue jusqu'à l'accueil au bout du couloir à gauche.","Au bout du couloir à droite.","Directement à l'accueil du 1ᵉʳ étage."], c:1},
    {id:2, doc:{type:"panneau",title:"LAVERIE SOLEIL",lines:["Machine à laver : 4,00 $ (cycle 45 min)","Séchoir : 2,50 $ (cycle 30 min)","Ouvert 7j/7 — 7h à 22h","Dernier lavage accepté à 21h00"],color:"#3498db"}, q:"Peut-on lancer un lavage à 21h30 ?",
      o:["Oui, la laverie ferme à 22h.","Non, le dernier lavage est à 21h.","Oui, si le cycle finit avant 22h.","Non, la laverie ferme à 21h."], c:1},
    {id:3, doc:{type:"sms",from:"Papa",time:"18:20",message:"J'ai garé la voiture au parking souterrain niveau -2, place B14. Les clés sont sous le tapis de l'entrée. Ne rentre pas trop tard !"}, q:"Où sont les clés de la voiture ?",
      o:["Dans la voiture, place B14.","Sous le tapis de l'entrée de la maison.","Au parking souterrain niveau -2.","Papa les a gardées avec lui."], c:1},
    {id:4, doc:{type:"affiche",title:"PISCINE MUNICIPALE",lines:["Nage libre : 6h – 8h et 12h – 13h","Cours de natation : 9h – 11h30","Bain libre familial : 15h – 17h","Bonnet obligatoire — Maillot de bain uniquement"],color:"#00bcd4"}, q:"À quelle heure un parent peut-il nager avec son enfant ?",
      o:["De 6h à 8h.","De 15h à 17h.","De 12h à 13h.","À toute heure d'ouverture."], c:1},
    {id:5, doc:{type:"email",from:"Boutique en ligne ModePlus",to:"client@mail.ca",subject:"Votre retour a été reçu",body:"Bonjour,\nNous avons bien reçu l'article retourné (robe réf. 4412). Le remboursement sera effectué sous 5 à 10 jours ouvrables sur votre mode de paiement original. Note : les frais de livraison initiaux ne sont pas remboursables."}, q:"Le client sera-t-il remboursé intégralement ?",
      o:["Oui, la totalité du montant sera remboursée.","Non, les frais de livraison initiaux ne sont pas remboursés.","Non, seule la moitié du prix sera remboursée.","Oui, y compris les frais de retour."], c:1},
    {id:6, doc:{type:"panneau",title:"PROMOTION",lines:["2 pizzas achetées = la 3ᵉ GRATUITE","Sur les formats MOYENS uniquement","Non cumulable avec d'autres offres","Valable en magasin jusqu'au 15 mars"],color:"#e67e22"}, q:"Cette offre s'applique-t-elle aux grandes pizzas ?",
      o:["Oui, à tous les formats.","Non, uniquement aux formats moyens.","Oui, mais seulement en livraison.","Non, uniquement aux petits formats."], c:1},
    {id:7, doc:{type:"carte_postale",dest:"Mamie Jeanne\n45 rue des Lilas\nSherbrooke (QC)",body:"Chère Mamie, on est arrivés à Percé hier soir. Le rocher est encore plus beau en vrai ! Demain on fait une excursion en bateau pour voir les fous de Bassan. Il fait froid mais on s'amuse. On rentre samedi.",signature:"Bisous, Emma et Lucas"}, q:"Quand Emma et Lucas sont-ils arrivés ?",
      o:["Aujourd'hui.","Hier soir.","Samedi.","Il y a deux jours."], c:1},
    {id:8, doc:{type:"panneau",lines:["📋 SALLE D'EXAMEN","Calculatrices autorisées","Téléphones : INTERDITS","Dictionnaires : NON autorisés","Durée : 3 heures"],color:"#34495e"}, q:"Quels appareils peut-on utiliser ?",
      o:["Les calculatrices et les téléphones.","Les calculatrices uniquement.","Les dictionnaires et les calculatrices.","Aucun appareil n'est autorisé."], c:1},
    {id:9, doc:{type:"note",body:"Cher locataire,\nVotre bail arrive à échéance le 30 juin. Si vous souhaitez le renouveler, merci de nous informer par écrit avant le 31 mars. Passé cette date, nous considérerons que vous quittez l'appartement.\n— Gestion Immo Plus"}, q:"Que se passe-t-il si le locataire ne répond pas avant le 31 mars ?",
      o:["Le bail est automatiquement renouvelé.","Le propriétaire considère qu'il quitte l'appartement.","Le loyer augmente de 10 %.","Le locataire a un mois supplémentaire pour décider."], c:1},
    {id:10, doc:{type:"menu",restaurant:"☕ Café Moka — Petit-déjeuner",items:[{name:"Formule A : Croissant + café",price:"4,50 $"},{name:"Formule B : Œufs + bacon + toast + café",price:"9,75 $"},{name:"Formule C : Pancakes + jus d'orange",price:"8,25 $"}],footer:"Supplément café refill : 1,50 $. Servi jusqu'à 11h."}, q:"Quelle formule inclut du jus d'orange ?",
      o:["La formule A.","La formule B.","La formule C.","Toutes les formules."], c:2},
    // B1/B2
    {id:11, doc:{type:"article",source:"La Presse — Emploi",body:"Le taux de chômage au Canada a baissé à 5,2 %, son plus bas niveau depuis 2019. Paradoxalement, les entreprises peinent toujours à recruter : 60 % des PME déclarent avoir des postes vacants depuis plus de trois mois. Les experts pointent un décalage entre les compétences recherchées et celles des candidats disponibles."}, q:"Comment expliquer le paradoxe décrit dans l'article ?",
      o:["Il n'y a pas assez de chômeurs pour combler les postes.","Les compétences des candidats ne correspondent pas aux besoins des entreprises.","Les entreprises offrent des salaires trop bas.","Le taux de chômage est en réalité plus élevé que les statistiques officielles."], c:1},
    {id:12, doc:{type:"lettre",header:"Objet : Relance — Facture n° 2026-0892 impayée",body:"Madame, Monsieur,\n\nSauf erreur de notre part, la facture n° 2026-0892 d'un montant de 347,50 $ émise le 15 janvier reste impayée à ce jour. Nous vous prions de bien vouloir procéder au règlement dans les 15 jours suivant la réception de ce courrier. À défaut, des intérêts de retard seront appliqués conformément à nos conditions générales.",signature:"Service comptabilité\nDistributeurs Apex inc."}, q:"Que risque le destinataire s'il ne paie pas dans les 15 jours ?",
      o:["Une action en justice immédiate.","L'application d'intérêts de retard.","La suspension de son compte client.","L'envoi d'un huissier."], c:1},
    {id:13, doc:{type:"article",source:"Le Devoir — Société",body:"Les banques alimentaires québécoises ont enregistré 1,9 million de visites en un seul mois, un record. L'inflation alimentaire frappe, mais un phénomène nouveau apparaît : 30 % des nouveaux demandeurs ont un emploi à temps plein. Ce ne sont plus seulement les sans-emploi qui ont faim, mais des travailleurs dont le salaire ne couvre plus les besoins de base."}, q:"Quelle est la nouveauté mise en lumière par cet article ?",
      o:["L'augmentation générale du nombre de visites.","Le fait que des travailleurs à temps plein aient recours aux banques alimentaires.","La hausse du prix des aliments.","Le manque de bénévoles dans les banques alimentaires."], c:1},
    {id:14, doc:{type:"article",source:"Radio-Canada — Santé publique",body:"Le Québec a interdit les saveurs dans les cigarettes électroniques pour réduire leur attrait chez les jeunes. Six mois plus tard, les ventes légales ont chuté de 40 %, mais les saisies de produits de contrebande aromatisés ont triplé. Les opposants à la loi y voient la preuve que l'interdiction a simplement déplacé le problème vers le marché noir."}, q:"Quel effet imprévu la loi a-t-elle eu ?",
      o:["Les jeunes ont complètement arrêté de vapoter.","La contrebande de produits aromatisés a fortement augmenté.","Les ventes légales de cigarettes traditionnelles ont augmenté.","Le nombre de fumeurs adultes a baissé."], c:1},
    {id:15, doc:{type:"article",source:"Le Soleil — Immigration",body:"Le programme d'immigration au Québec exige un niveau NCLC 7 en français pour la plupart des catégories économiques. Or, de nombreux candidats francophones d'Afrique subsaharienne échouent au test malgré un français courant, car l'examen évalue un registre formel éloigné de leur usage quotidien. Le paradoxe : des francophones natifs recalés à un test de français."}, q:"Pourquoi des francophones natifs échouent-ils au test ?",
      o:["Parce que leur niveau de français est insuffisant.","Parce que l'examen évalue un registre formel différent de leur usage courant.","Parce que le niveau NCLC 7 est trop élevé pour tout le monde.","Parce qu'ils ne se sont pas préparés à l'examen."], c:1},
    {id:16, doc:{type:"article",source:"La Presse — Urbanisme",body:"Montréal a inauguré une nouvelle piste cyclable protégée de 15 km. Les premiers chiffres montrent 8 000 passages quotidiens. Les commerçants riverains, qui craignaient une perte de clientèle, constatent au contraire une hausse de 12 % de leur chiffre d'affaires — les cyclistes s'arrêtent plus facilement que les automobilistes."}, q:"Qu'est-il arrivé aux commerces situés le long de la piste cyclable ?",
      o:["Ils ont perdu de la clientèle comme prévu.","Leur chiffre d'affaires a augmenté contrairement aux craintes initiales.","Ils ont dû fermer à cause du bruit.","Ils n'ont constaté aucun changement."], c:1},
    {id:17, doc:{type:"article",source:"Le Devoir — Logement",body:"Le taux d'inoccupation des logements à Montréal est tombé à 1,5 %, bien en dessous du seuil d'équilibre de 3 %. Les locataires acceptent désormais des logements plus petits, plus chers et plus éloignés. Certains propriétaires exigent même des « entrevues » avec les candidats, une pratique légale mais éthiquement discutable."}, q:"Que signifie un taux d'inoccupation de 1,5 % ?",
      o:["Qu'il y a suffisamment de logements pour tout le monde.","Qu'il y a très peu de logements disponibles par rapport à la demande.","Que 1,5 % des locataires ne paient pas leur loyer.","Que les loyers ont baissé de 1,5 %."], c:1},
    {id:18, doc:{type:"article",source:"L'actualité — Éducation",body:"Le ministère de l'Éducation du Québec envisage d'interdire les téléphones en classe au primaire et au secondaire. Les enseignants sont divisés : certains y voient un outil pédagogique indispensable pour les recherches et les applications éducatives, tandis que d'autres constatent que les élèves passent plus de temps sur les réseaux sociaux que sur les exercices."}, q:"Pourquoi certains enseignants s'opposent-ils à l'interdiction ?",
      o:["Parce que les parents y sont opposés.","Parce qu'ils considèrent le téléphone comme un outil pédagogique utile.","Parce que les élèves apprendraient moins bien sans.","Parce que l'interdiction est impossible à appliquer."], c:1},
    {id:19, doc:{type:"article",source:"Québec Science",body:"Une startup montréalaise a développé une technologie de captage du CO₂ directement dans l'air ambiant. L'installation pilote capture 500 tonnes par an — ce qui équivaut aux émissions annuelles de 100 voitures. Les critiques soulignent que le coût de 600 $ la tonne rend la technologie non viable sans subventions massives."}, q:"Quel est le principal obstacle à cette technologie ?",
      o:["Elle ne fonctionne pas en conditions réelles.","Son coût est trop élevé pour être viable sans subventions.","Elle produit plus de CO₂ qu'elle n'en capture.","Elle est dangereuse pour l'environnement."], c:1},
    {id:20, doc:{type:"article",source:"Le Devoir — Travail",body:"Le droit à la déconnexion, adopté en Ontario en 2022, oblige les entreprises de plus de 25 employés à définir une politique sur les communications hors des heures de travail. Deux ans plus tard, un sondage montre que 70 % des travailleurs continuent de répondre à des courriels le soir. Les chercheurs concluent que la loi, sans sanctions, relève davantage du symbole que de la protection réelle."}, q:"Pourquoi la loi sur la déconnexion est-elle jugée insuffisante ?",
      o:["Parce qu'elle ne s'applique qu'aux grandes entreprises.","Parce qu'en l'absence de sanctions, elle n'a pas changé les comportements.","Parce que les employés préfèrent travailler le soir.","Parce que les syndicats s'y opposent."], c:1},
    {id:21, doc:{type:"article",source:"Radio-Canada — Environnement",body:"Le fleuve Saint-Laurent abrite désormais une population résidente de 14 baleines à bosse, un phénomène nouveau. Les scientifiques l'attribuent au réchauffement des eaux qui attire de nouvelles proies. Cette bonne nouvelle pour le tourisme est toutefois tempérée par les risques accrus de collision avec les navires commerciaux."}, q:"Pourquoi la présence de baleines dans le Saint-Laurent est-elle à la fois positive et préoccupante ?",
      o:["Positive pour la pêche, préoccupante pour l'écosystème.","Positive pour le tourisme, préoccupante à cause des collisions avec les navires.","Positive pour la science, préoccupante pour les pêcheurs.","Positive pour l'environnement, préoccupante pour la navigation de plaisance."], c:1},
    {id:22, doc:{type:"article",source:"Le Journal de Montréal — Culture",body:"Le Musée des beaux-arts de Montréal a instauré la gratuité permanente pour les moins de 21 ans. La fréquentation des jeunes a bondi de 45 % en un an. Toutefois, le musée accuse un déficit de 2 millions de dollars et envisage d'augmenter le tarif adulte de 24 à 28 $."}, q:"Quelle conséquence la gratuité pour les jeunes a-t-elle eue sur le musée ?",
      o:["Elle a résolu les problèmes financiers du musée.","Elle a attiré plus de jeunes mais creusé le déficit.","Elle a réduit la fréquentation globale.","Elle a été abandonnée après un an."], c:1},
    {id:23, doc:{type:"article",source:"Le Devoir — Agriculture",body:"Le Québec produit 72 % du sirop d'érable mondial. Le changement climatique raccourcit la saison des sucres, mais un effet inattendu apparaît : les érables situés plus au nord, autrefois improductifs, commencent à donner du sirop. La zone de production se déplace progressivement vers le Saguenay et la Côte-Nord."}, q:"Quel effet inattendu le changement climatique a-t-il sur la production d'érable ?",
      o:["La qualité du sirop s'est dégradée.","De nouvelles zones de production apparaissent plus au nord.","La production a complètement cessé dans le sud du Québec.","Les érables sont remplacés par d'autres espèces d'arbres."], c:1},
    {id:24, doc:{type:"article",source:"La Presse — Sport",body:"Hockey Canada a annoncé un programme de bourses de 10 millions de dollars pour rendre le hockey accessible aux familles à faible revenu. Le coût moyen de l'équipement dépasse 1 200 $ par saison. Les critiques notent que le programme ne couvre que l'équipement et ignore les frais d'inscription aux ligues (souvent 2 000 $ supplémentaires), ce qui limite son impact réel."}, q:"Pourquoi le programme de bourses est-il jugé insuffisant ?",
      o:["Parce que 10 millions est un budget trop faible.","Parce qu'il ne couvre pas les frais d'inscription qui sont souvent plus élevés que l'équipement.","Parce que les familles ne savent pas que le programme existe.","Parce que le hockey n'intéresse plus les jeunes."], c:1},
    // C1/C2
    {id:25, doc:{type:"article",source:"Essai — Multiculturalisme",body:"Le multiculturalisme canadien célèbre la diversité en surface tout en maintenant des structures qui la pénalisent en profondeur. Un CV portant un nom à consonance arabe reçoit 40 % de réponses en moins qu'un CV identique avec un nom francophone. L'ironie est cruelle : le pays qui se vante d'être le plus ouvert au monde discrimine systématiquement ceux qu'il invite à venir."}, q:"Quelle contradiction l'auteur met-il en lumière ?",
      o:["Le Canada accueille trop d'immigrants.","Le discours d'ouverture coexiste avec une discrimination systémique à l'embauche.","Les immigrants ne s'intègrent pas assez.","Le multiculturalisme devrait être abandonné au profit de l'assimilation."], c:1},
    {id:26, doc:{type:"text",body:"Les dimanches de son enfance sentaient le sucre à la crème et la lessive fraîche. C'étaient des jours immobiles, où le temps semblait hésiter. Émile avait depuis traversé des océans. Mais il suffisait d'une odeur — vanille, savon — pour que tout s'effondre : non pas le souvenir de ces dimanches, mais la certitude brutale qu'il ne les vivrait plus jamais tels qu'ils avaient été."}, q:"Que provoque l'odeur chez Émile ?",
      o:["Le bonheur de retrouver son enfance.","La conscience douloureuse que ces moments sont irréversiblement perdus.","L'envie de retourner dans son pays natal.","La nostalgie heureuse d'un passé idéalisé."], c:1},
    {id:27, doc:{type:"article",source:"Éthique et IA — Revue",body:"La discrimination algorithmique est d'autant plus pernicieuse qu'elle se drape dans l'objectivité. Un algorithme de tri de CV qui défavorise les femmes ne « décide » pas d'être sexiste — il reproduit les biais contenus dans les données historiques sur lesquelles il a été entraîné. Le problème n'est pas la machine, mais le miroir qu'elle tend à nos propres préjugés."}, q:"Selon l'auteur, d'où vient la discrimination algorithmique ?",
      o:["De la programmation intentionnellement biaisée des développeurs.","Des biais historiques présents dans les données d'entraînement.","De la volonté des entreprises de discriminer.","De l'incapacité technique des algorithmes à traiter des données humaines."], c:1},
    {id:28, doc:{type:"article",source:"Droit constitutionnel",body:"La clause « nonobstant » de la Charte canadienne permet aux gouvernements de suspendre temporairement certains droits fondamentaux. Ses défenseurs y voient un garde-fou démocratique contre la « judiciarisation du politique ». Ses détracteurs y voient une brèche par laquelle les droits des minorités peuvent être sacrifiés à la volonté de la majorité."}, q:"Quel argument les détracteurs de la clause avancent-ils ?",
      o:["Elle rend la Charte inutile.","Elle permet de sacrifier les droits des minorités au nom de la majorité.","Elle est utilisée trop rarement pour être utile.","Elle donne trop de pouvoir aux juges."], c:1},
    {id:29, doc:{type:"text",body:"Sarah n'écrivait jamais de lettres. Mais ce matin-là, elle comprit que le courriel ne suffirait pas. Ce qu'elle avait à dire exigeait le temps du stylo, la maladresse des ratures, l'impossibilité de cliquer sur « supprimer ». Il fallait que les mots résistent à la tentation de l'effacement — qu'ils existent, une fois tracés, avec la même irréversibilité que ce qu'ils nommaient."}, q:"Pourquoi Sarah choisit-elle le stylo plutôt que le courriel ?",
      o:["Parce que son ordinateur est en panne.","Parce que l'irréversibilité de l'écriture correspond à l'irréversibilité de ce qu'elle veut exprimer.","Parce qu'elle veut impressionner le destinataire par un geste élégant.","Parce qu'elle a l'habitude d'écrire à la main."], c:1},
    {id:30, doc:{type:"article",source:"Essai — Progrès",body:"Le XXᵉ siècle a démenti la vision linéaire du progrès : Auschwitz et Hiroshima sont les produits de la même rationalité qui a inventé la pénicilline et envoyé l'homme sur la Lune. Repenser le progrès, ce n'est pas le nier — c'est reconnaître qu'une même avancée peut simultanément libérer et détruire, et que cette ambivalence est constitutive de la condition moderne."}, q:"Que propose l'auteur concernant le progrès ?",
      o:["De l'abandonner comme concept.","De le reconcevoir comme un processus fondamentalement ambivalent.","De revenir à une vision pré-moderne du monde.","De séparer le progrès technique du progrès moral."], c:1},
    {id:31, doc:{type:"article",source:"Économie circulaire",body:"Le recyclage ne concerne que 8,6 % des matériaux consommés mondialement. Plus troublant encore : le taux de recyclage est en baisse depuis 2018, malgré la multiplication des politiques de tri. L'explication tient en un chiffre : la production mondiale de matériaux vierges augmente de 3 % par an, diluant les efforts de recyclage dans un océan de consommation croissante."}, q:"Pourquoi le taux de recyclage baisse-t-il malgré les politiques de tri ?",
      o:["Les gens refusent de trier leurs déchets.","La production de matériaux vierges croît plus vite que le recyclage.","Les technologies de recyclage sont devenues obsolètes.","Les gouvernements ont réduit leurs investissements dans le tri."], c:1},
    {id:32, doc:{type:"article",source:"Philosophie politique",body:"Les « bulles de filtres » algorithmiques ne créent pas la polarisation politique — elles l'accélèrent. Les études montrent que la polarisation existait avant les réseaux sociaux. Ce que les algorithmes ajoutent, c'est la vitesse et l'intensité : ils transforment un désaccord en hostilité, une différence d'opinion en incompatibilité identitaire."}, q:"Selon l'auteur, quel est le rôle précis des algorithmes dans la polarisation ?",
      o:["Ils en sont la cause unique et première.","Ils accélèrent et intensifient une polarisation préexistante.","Ils n'ont aucun effet sur la polarisation politique.","Ils réduisent la polarisation en exposant les gens à des opinions diverses."], c:1},
    {id:33, doc:{type:"article",source:"Essai — Temporalité",body:"Nous ne manquons pas de temps — nous manquons de stabilité temporelle. L'accélération sociale a rendu précaires les repères qui structuraient une vie : un métier pour la vie, un couple durable, un lieu d'ancrage. Cette précarité n'est pas seulement économique ; elle est existentielle. L'angoisse contemporaine n'est pas celle de l'horloge qui avance, mais celle du sol qui se dérobe."}, q:"Quelle distinction fondamentale l'auteur établit-il ?",
      o:["Entre le temps objectif et le temps subjectif.","Entre le manque de temps et le manque de stabilité dans le temps.","Entre l'accélération technologique et l'accélération sociale.","Entre les générations anciennes et les générations actuelles."], c:1},
    {id:34, doc:{type:"article",source:"Justice climatique",body:"Les 10 % les plus riches de la planète produisent 50 % des émissions mondiales de CO₂. Les 50 % les plus pauvres en produisent 10 %. Pourtant, ce sont ces derniers qui subissent l'essentiel des conséquences : sécheresses, inondations, famines. La justice climatique n'est pas un supplément d'âme — c'est la condition de légitimité de toute politique environnementale."}, q:"Que signifie « la justice climatique est la condition de légitimité » ?",
      o:["Sans redistribution des coûts, les politiques environnementales seront rejetées par les plus vulnérables.","La justice climatique est un concept inutile.","Les pays riches doivent arrêter toute production industrielle.","Les pays pauvres doivent accepter de polluer moins."], c:0},
    {id:35, doc:{type:"article",source:"Sociolinguistique",body:"Le code-switching entre français et anglais à Montréal ne relève pas de la paresse linguistique. Les locuteurs bilingues alternent stratégiquement : le français pour marquer l'appartenance communautaire, l'anglais pour signaler une compétence professionnelle, le mélange pour créer une connivence avec ceux qui partagent cette double identité. Chaque alternance est un acte identitaire."}, q:"Selon l'auteur, pourquoi les Montréalais alternent-ils entre français et anglais ?",
      o:["Parce qu'ils ne maîtrisent ni l'un ni l'autre parfaitement.","Pour remplir des fonctions identitaires et sociales précises.","Parce que l'anglais est plus pratique pour le travail.","Par habitude inconsciente héritée de l'enfance."], c:1},
    {id:36, doc:{type:"text",body:"Le pardon, tel qu'on le lui avait enseigné, laissait intacte la relation entre victime et bourreau — il effaçait la dette sans transformer le créancier. Ce qu'Amina cherchait n'avait pas de nom. Non pas oublier, non pas pardonner, mais atteindre un lieu intérieur où la blessure, sans être niée, cessait d'être l'axe autour duquel tout gravitait."}, q:"Que rejette Amina dans le pardon tel qu'il est habituellement conçu ?",
      o:["L'idée de la réconciliation.","Le fait qu'il efface la dette sans transformer la personne blessée.","La composante religieuse du pardon.","L'obligation de confronter celui qui l'a blessée."], c:1},
    {id:37, doc:{type:"article",source:"Hospitalité — Derrida",body:"L'hospitalité inconditionnelle — accueillir l'autre sans condition, sans même demander son nom — est un idéal éthiquement nécessaire mais pratiquement impossible. Toute hospitalité réelle impose des limites : une porte, un seuil, des conditions d'entrée. Derrida ne voit pas là un échec mais une tension féconde : c'est PARCE que l'idéal est inatteignable qu'il nous oblige à repousser sans cesse nos limites."}, q:"Pourquoi Derrida considère-t-il l'impossibilité de l'hospitalité absolue comme « féconde » ?",
      o:["Parce qu'elle prouve que l'hospitalité est une illusion.","Parce qu'elle nous pousse constamment à élargir nos limites.","Parce qu'elle justifie les politiques restrictives d'immigration.","Parce qu'elle libère l'hôte de toute obligation morale."], c:1},
    {id:38, doc:{type:"article",source:"Capitalisme de surveillance — Zuboff",body:"L'utilisateur de services « gratuits » n'est pas le client — il est la matière première. Ce qui est extrait et monnayé, ce n'est pas son attention (comme le pensait la génération précédente de critiques), mais son comportement futur. Les données permettent de prédire — et, insidieusement, de modifier — ce que nous ferons demain. Le produit vendu aux annonceurs n'est pas la publicité : c'est la certitude."}, q:"Quelle distinction l'auteur fait-elle par rapport aux critiques antérieures ?",
      o:["L'attention n'est plus captée par les écrans.","Ce n'est pas l'attention mais le comportement futur qui est monnayé.","Les services gratuits sont devenus payants.","Les utilisateurs sont désormais conscients de cette exploitation."], c:1},
    {id:39, doc:{type:"article",source:"Essai final — Anthropocène",body:"La question de l'Anthropocène n'est pas technique — nous disposons des solutions. Elle est civilisationnelle. Elle exige un renoncement : non pas à la technologie, mais au récit qui la sous-tend — celui d'un sujet humain souverain, extérieur à la nature, dont la vocation serait de la maîtriser. Tant que nous penserons la Terre comme un « environnement » qui nous « entoure », nous resterons dans la logique qui l'a dévastée."}, q:"Selon l'auteur, quel changement est nécessaire ?",
      o:["Abandonner toute forme de technologie.","Renoncer à la conception de l'humain comme maître extérieur à la nature.","Investir massivement dans les énergies renouvelables.","Créer un gouvernement mondial de l'environnement."], c:1},
];

function sc(a){let x=0,y=0,z=0;Q.forEach((q,i)=>{const ok=a[i]===q.c;if(i<10&&ok)x++;else if(i<24&&ok)y++;else if(i>=24&&ok)z++});const xp=x/10,yp=y/14,zp=z/15,t=x+y+z,tp=t/39;let n;if(zp>=.8&&yp>=.7)n=tp>=.85?10:tp>=.75?9:8;else if(zp>=.5&&yp>=.6)n=tp>=.65?7:6;else if(yp>=.5&&xp>=.7)n=tp>=.55?6:5;else if(xp>=.7&&yp>=.3)n=4;else if(xp>=.5)n=3;else n=2;const lv=n>=9?"C2":n>=7?"C1":n>=6?"B2":n>=4?"B1":n>=3?"A2":"A1";return{nclc:n,level:lv,total:t,a1a2:x,b1b2:y,c1c2:z,xp,yp,zp}}

const C={bg:"#080c16",s1:"#0d1425",cy:"#00d4ff",ind:"#6366f1",gn:"#10b981",bl:"#3b82f6",rd:"#ef4444",am:"#f59e0b",tx:"#e2e8f0",txm:"#94a3b8",txd:"#64748b"};
const base={fontFamily:"system-ui,sans-serif",background:C.bg,color:C.tx,minHeight:"100vh"};
const b1={fontWeight:700,fontSize:".85rem",letterSpacing:".08em",textTransform:"uppercase",background:`linear-gradient(135deg,${C.cy},${C.ind})`,color:"#fff",border:"none",padding:".9rem 2.5rem",borderRadius:8,cursor:"pointer"};
const b2={fontSize:".8rem",background:"transparent",color:C.txm,border:"1px solid rgba(0,212,255,.15)",padding:".6rem 1.2rem",borderRadius:6,cursor:"pointer",fontFamily:"inherit"};
const b3={...b1,fontSize:".75rem",padding:".6rem 1.2rem",background:`linear-gradient(135deg,${C.gn},#059669)`};

export default function App(){
  const nav=useNavigate();
  const[pg,setPg]=useState("home");
  const[ci,setCi]=useState(0);
  const[ans,setAns]=useState({});
  const[sec,setSec]=useState(3600);
  const[on,setOn]=useState(false);
  const[pop,setPop]=useState(false);
  const[fl,setFl]=useState(new Set());
  const[nv,setNv]=useState(false);
  const[res,setRes]=useState(null);
  const tr=useRef(null);

  useEffect(()=>{if(!on)return;tr.current=setInterval(()=>setSec(p=>{if(p<=1){clearInterval(tr.current);return 0}return p-1}),1000);return()=>clearInterval(tr.current)},[on]);
  useEffect(()=>{if(sec===0&&on){setOn(false);setRes(sc(ans));setPg("results")}},[sec,on,ans]);

  const go=()=>{setAns({});setCi(0);setSec(3600);setOn(true);setFl(new Set());setNv(false);setPg("quiz")};
  const fin=()=>{setOn(false);clearInterval(tr.current);setRes(sc(ans));setPg("results")};
  const pk=(i,j)=>setAns(p=>({...p,[i]:j}));
  const fg=i=>{setFl(p=>{const n=new Set(p);n.has(i)?n.delete(i):n.add(i);return n})};
  const fm=s=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;
  const ct=Object.keys(ans).length;
  const L=["A","B","C","D"];

  if(pg==="home")return(
    <div style={base}><div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",minHeight:"100vh",padding:"2rem",textAlign:"center"}}>
      <div style={{fontSize:".65rem",color:C.cy,letterSpacing:".15em",textTransform:"uppercase",marginBottom:"2rem",fontFamily:"monospace"}}>FLAB GAMES</div>
      <h1 style={{fontSize:"clamp(2rem,7vw,3.5rem)",fontWeight:900,background:`linear-gradient(135deg,#fff,${C.cy},${C.ind})`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",lineHeight:1,marginBottom:8}}>ESCAPE LAB</h1>
      <p style={{fontSize:"clamp(.75rem,2vw,1rem)",color:C.txm,letterSpacing:".15em",textTransform:"uppercase",marginBottom:"1.5rem"}}>S{"\u00e9"}rie Bravo {"\u2014"} TCF Canada</p>
      <p style={{fontSize:".9rem",color:C.txd,maxWidth:460,lineHeight:1.6,marginBottom:"2.5rem"}}>39 questions avec vrais pi{"\u00e8"}ges. 60 minutes. A1{"\u2192"}C2.</p>
      <button style={b1} onClick={go}>COMMENCER</button>
      <div style={{display:"flex",gap:"2rem",marginTop:"2.5rem",flexWrap:"wrap",justifyContent:"center"}}>
        {[["39","Questions"],["60","Min"],["NCLC","Score"]].map(([v,l])=>(<div key={l} style={{textAlign:"center"}}><div style={{fontWeight:700,fontSize:"1.3rem",color:C.cy}}>{v}</div><div style={{fontSize:".6rem",color:C.txd,textTransform:"uppercase"}}>{l}</div></div>))}
      </div>
    </div></div>
  );

  if(pg==="quiz"){const q=Q[ci],ll=ci<10?"A1/A2":ci<24?"B1/B2":"C1/C2",lc=ci<10?C.gn:ci<24?C.bl:C.ind,tc=sec<=300?C.rd:sec<=900?C.am:C.cy;
  return(<div style={base}>
    <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:".6rem 1rem",background:C.s1,borderBottom:"1px solid rgba(0,212,255,.1)",position:"sticky",top:0,zIndex:50,flexWrap:"wrap",gap:4}}>
      <span style={{fontWeight:700,fontSize:".75rem",color:C.cy}}>ESCAPE LAB</span>
      <div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontWeight:700,fontSize:"1.1rem",color:tc,fontFamily:"monospace"}}>{fm(sec)}</span><span style={{fontSize:".65rem",color:C.txd,fontFamily:"monospace"}}>{ct}/39</span></div>
      <div style={{display:"flex",gap:4}}>
        <button onClick={()=>fg(ci)} style={{...b2,padding:"4px 8px",borderColor:fl.has(ci)?C.ind:"rgba(0,212,255,.15)",color:fl.has(ci)?C.ind:C.txm}}>{"\u2691"}</button>
        <button onClick={()=>setNv(!nv)} style={{...b2,padding:"4px 8px"}}>{"\u2630"}</button>
      </div>
    </div>
    <div style={{height:3,background:"#121a32"}}><div style={{height:"100%",width:`${(ct/39)*100}%`,background:`linear-gradient(90deg,${C.cy},${C.ind})`,transition:"width .3s"}}/></div>
    <div style={{maxWidth:780,margin:"0 auto",padding:"1.5rem 1rem",display:"flex",flexDirection:"column",minHeight:"calc(100vh - 60px)"}}>
      <span style={{display:"inline-block",padding:"3px 10px",borderRadius:100,fontSize:".6rem",fontWeight:700,marginBottom:12,border:`1px solid ${lc}33`,color:lc,background:`${lc}11`,alignSelf:"flex-start"}}>Q{ci+1} {"\u00b7"} {ll}</span>
      <Doc d={q.doc}/>
      <p style={{fontWeight:600,fontSize:".95rem",marginBottom:12,color:"#fff"}}>{q.q}</p>
      <div style={{display:"flex",flexDirection:"column",gap:8,marginBottom:"1.5rem"}}>
        {q.o.map((o,i)=>(<button key={i} onClick={()=>pk(ci,i)} style={{display:"flex",alignItems:"flex-start",gap:10,padding:".8rem 1rem",background:ans[ci]===i?"rgba(0,212,255,.06)":C.s1,border:`1px solid ${ans[ci]===i?C.cy:"rgba(0,212,255,.1)"}`,borderRadius:8,cursor:"pointer",textAlign:"left",fontFamily:"inherit",fontSize:".85rem",color:C.tx,lineHeight:1.45,transition:"all .15s"}}>
          <span style={{flexShrink:0,width:26,height:26,borderRadius:5,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"monospace",fontWeight:700,fontSize:".7rem",background:ans[ci]===i?C.cy:"#121a32",color:ans[ci]===i?C.bg:C.txd}}>{L[i]}</span>
          <span>{o}</span>
        </button>))}
      </div>
      <div style={{display:"flex",justifyContent:"space-between",marginTop:"auto",paddingTop:"1rem",gap:8}}>
        <button style={{...b2,opacity:ci===0?.3:1}} onClick={()=>setCi(Math.max(0,ci-1))} disabled={ci===0}>{"\u2190"} Pr{"\u00e9"}c.</button>
        {ci<38?<button style={b2} onClick={()=>setCi(ci+1)}>Suiv. {"\u2192"}</button>:<button style={b3} onClick={()=>setPop(true)}>TERMINER</button>}
      </div>
    </div>
    {nv&&<div onClick={e=>{if(e.target===e.currentTarget)setNv(false)}} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.6)",zIndex:100,display:"flex",justifyContent:"flex-end"}}>
      <div style={{width:"min(360px,88vw)",background:C.s1,padding:"1.2rem",overflowY:"auto",borderLeft:"1px solid rgba(0,212,255,.1)"}}>
        <div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><span style={{fontWeight:700,fontSize:".8rem",color:C.cy}}>NAVIGATION</span><button style={{...b2,padding:"2px 8px"}} onClick={()=>setNv(false)}>{"\u2715"}</button></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(38px,1fr))",gap:5,marginBottom:12}}>
          {Q.map((_,i)=>(<div key={i} onClick={()=>{setCi(i);setNv(false)}} style={{aspectRatio:"1",borderRadius:5,border:`1px solid ${i===ci?C.cy:ans[i]!=null?C.cy+"40":"rgba(0,212,255,.1)"}`,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"monospace",fontSize:".65rem",fontWeight:700,cursor:"pointer",background:ans[i]!=null?C.cy+"1a":"#121a32",color:ans[i]!=null?C.cy:C.txd,boxShadow:i===ci?`0 0 8px ${C.cy}40`:"none",position:"relative"}}>{i+1}{fl.has(i)&&<span style={{position:"absolute",top:-2,right:1,fontSize:".5rem",color:C.am}}>{"\u2691"}</span>}</div>))}
        </div>
        <button style={{...b3,width:"100%"}} onClick={()=>{setNv(false);setPop(true)}}>TERMINER</button>
      </div>
    </div>}
    {pop&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.7)",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",padding:"1rem"}}>
      <div style={{background:C.s1,border:"1px solid rgba(0,212,255,.1)",borderRadius:14,padding:"1.8rem",maxWidth:400,width:"100%",textAlign:"center"}}>
        <div style={{fontSize:"2rem",marginBottom:8}}>{"\u26a0\ufe0f"}</div>
        <div style={{fontWeight:700,color:C.cy,marginBottom:8}}>Terminer ?</div>
        <div style={{fontSize:".82rem",color:C.txm,marginBottom:"1.2rem"}}>{ct}/39.{39-ct>0&&<> {39-ct} sans r{"\u00e9"}ponse.</>}</div>
        <div style={{display:"flex",gap:8,justifyContent:"center"}}><button style={b2} onClick={()=>setPop(false)}>Continuer</button><button style={b3} onClick={()=>{setPop(false);fin()}}>Confirmer</button></div>
      </div>
    </div>}
  </div>)}

  if(pg==="results"&&res){const nc=["#ef4444","#f97316","#f59e0b","#eab308","#84cc16","#22c55e","#10b981","#06b6d4","#3b82f6","#6366f1"];
  return(<div style={base}><div style={{display:"flex",flexDirection:"column",alignItems:"center",padding:"2.5rem 1.2rem"}}>
    <div style={{fontSize:".65rem",color:C.txd,fontFamily:"monospace",letterSpacing:".1em",marginBottom:6}}>S{"\u00c9"}RIE BRAVO</div>
    <div style={{fontSize:"3.5rem",fontWeight:900,background:`linear-gradient(135deg,${C.cy},${C.ind})`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>{res.level}</div>
    <div style={{fontFamily:"monospace",fontSize:".85rem",color:C.txm,marginTop:4,marginBottom:"2rem"}}>NCLC : {res.nclc}/10</div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:8,maxWidth:560,width:"100%",marginBottom:"1.5rem"}}>
      {[["Total",res.total,39,C.cy],["A1/A2",res.a1a2,10,C.gn],["B1/B2",res.b1b2,14,C.bl],["C1/C2",res.c1c2,15,C.ind]].map(([l,v,m,c])=>(<div key={l} style={{background:C.s1,border:"1px solid rgba(0,212,255,.1)",borderRadius:8,padding:"1rem",textAlign:"center"}}><div style={{fontSize:".6rem",color:C.txd,fontFamily:"monospace",marginBottom:4}}>{l}</div><div style={{fontWeight:700,fontSize:"1.4rem",color:c}}>{v}/{m}</div><div style={{fontSize:".65rem",color:C.txd}}>{Math.round(v/m*100)}%</div></div>))}
    </div>
    {[["A1/A2",res.xp,C.gn],["B1/B2",res.yp,C.bl],["C1/C2",res.zp,C.ind]].map(([l,p,c])=>(<div key={l} style={{display:"flex",alignItems:"center",gap:8,marginBottom:8,width:"100%",maxWidth:420}}><span style={{fontFamily:"monospace",fontSize:".7rem",color:C.txd,width:42,textAlign:"right"}}>{l}</span><div style={{flex:1,height:7,background:"#121a32",borderRadius:100,overflow:"hidden"}}><div style={{height:"100%",width:`${p*100}%`,background:c,borderRadius:100}}/></div><span style={{fontFamily:"monospace",fontSize:".7rem",color:C.txm,width:32}}>{Math.round(p*100)}%</span></div>))}
    <div style={{display:"flex",gap:2,margin:"1.5rem 0",maxWidth:420,width:"100%"}}>
      {[1,2,3,4,5,6,7,8,9,10].map(n=>(<div key={n} style={{flex:1,height:28,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700,fontSize:".6rem",borderRadius:3,background:n===res.nclc?nc[n-1]:"#121a32",color:n===res.nclc?"#fff":C.txd,transform:n===res.nclc?"scaleY(1.3)":"none"}}>{n}</div>))}
    </div>
    <div style={{display:"flex",gap:8,marginTop:"1rem"}}><button style={b1} onClick={go}>RECOMMENCER</button><button style={b2} onClick={()=>nav("/")}>TOUTES LES S\u00c9RIES</button></div>
  </div></div>)}
  return null;
}
